using Google.Protobuf;
using MadTOM.Services;
using MADTOM.Plugins.Telemetry.Proto.V1;

namespace MadTOM.Tests;

public class ZstdCacheTests
{
    private static LODPoint[] Points(int count) => Enumerable.Range(0, count)
        .Select(i => new LODPoint(i * 1000000000L, i % 7, -i, i + 0.125)).ToArray();

    [Fact]
    public async Task PartialBlockExpiryAndQuotaShrinkKeepNewestSamplesWithinBudget()
    {
        var now = new DateTime(2026, 9, 20, 12, 0, 0, DateTimeKind.Utc);
        long nano = new DateTimeOffset(now).ToUnixTimeMilliseconds() * 1000000;
        var cache = new TelemetryHistoryCache(1, () => now);
        for (int i = 0; i < 256; i++)
            cache.Record("c", "n", nano - (256 - i) * 100000000L, new Dictionary<string, double> { ["cpu"] = i % 7 });
        cache.Configure(1, 2048, 4096, 30);
        Assert.InRange(cache.GetUsage(1).LiveBytes, 1, 2048);
        now = now.AddSeconds(40); // Cutoff moves into the sealed block.
        cache.Prune();
        Assert.InRange(cache.GetUsage(1).LiveBytes, 1, 2048);
        var points = await cache.QueryAsync("c", "n", "cpu", now.AddMinutes(-1), now, true,
            (_, _, _) => throw new Exception("local only"));
        Assert.NotEmpty(points);
        Assert.Equal(255 % 7, points[^1].Value);
        Assert.All(points, p => Assert.True(p.TimestampUnixNano >= new DateTimeOffset(now.AddMinutes(-1)).ToUnixTimeMilliseconds() * 1000000));
    }

    [Fact]
    public void DecodesKlauspostGoZstdFrame()
    {
        // Generated by Go klauspost/compress, SpeedFastest, window 1 MiB.
        var payload = Convert.FromBase64String("KLUv/WSvDJUAAFAKrBtpbnRlcm9wAVQKAy+iVWm56ps=");
        var response = ClientResponseCompression.Decode(new ListNodesResponse
        { ZstdPayload = ByteString.CopyFrom(payload), DecodedSize = 3503 }, new ClientPayloadCounter());
        Assert.Equal(string.Concat(Enumerable.Repeat("interop", 500)), response.CollectorName);
    }

    [Fact]
    public void SealedHistoryIsLosslessAcrossAppendPruneAndRangeReads()
    {
        var points = Points(1500);
        var history = new CompressedPointHistory();
        foreach (var point in points) history.Enqueue(point);
        Assert.True(history.CompressedBytes > 0);
        Assert.True(history.StorageBytes < history.RawBytes);
        Assert.Equal(points, history.ToArray());
        history.RemoveBefore(points[333].TimestampUnixNano);
        Assert.Equal(points.Skip(333), history.ToArray());
        Assert.Equal(points.Skip(700).Take(200), history.Read(points[700].TimestampUnixNano, points[899].TimestampUnixNano));
        history.RemoveBefore(points[899].TimestampUnixNano);
        Assert.Equal(points.Skip(899), history.ToArray());
        Assert.True(history.Covers(points[900].TimestampUnixNano, points[^1].TimestampUnixNano));
        history.RemoveBefore(long.MaxValue);
        Assert.Equal(0, history.Count);
        Assert.Equal(0, history.CompressedBytes);
    }

    [Fact]
    public void BlocksPreserveFloatingPointBitsAndSkipSmallPayloads()
    {
        var special = new[] { -0d, double.NaN, double.PositiveInfinity, double.Epsilon, double.MinValue };
        var points = Enumerable.Range(0, 256).Select(i => new LODPoint(i, special[i % special.Length], -0d, double.NaN)).ToArray();
        var decoded = new CompressedPointBlock(points).Decode();
        for (int i = 0; i < points.Length; i++)
        {
            Assert.Equal(BitConverter.DoubleToInt64Bits(points[i].Value), BitConverter.DoubleToInt64Bits(decoded[i].Value));
            Assert.Equal(BitConverter.DoubleToInt64Bits(points[i].Min), BitConverter.DoubleToInt64Bits(decoded[i].Min));
        }
        Assert.False(new CompressedPointBlock(points.Take(2).ToArray()).IsCompressed);
        var random = new byte[8192]; new Random(42).NextBytes(random);
        Assert.Null(ZstdCodec.CompressIfUseful(random));
    }

    [Fact]
    public async Task BothCachesCompressAndClearWithoutLosingLivePrecedence()
    {
        var now = new DateTime(2026, 9, 20, 12, 0, 0, DateTimeKind.Utc);
        long nano = new DateTimeOffset(now).ToUnixTimeMilliseconds() * 1000000;
        var cache = new TelemetryHistoryCache(60, () => now);
        var expected = Enumerable.Range(0, 1200).Select(i => new LODPoint(nano - (1200 - i) * 1000000000L, i % 7, i % 7, i % 7)).ToArray();
        foreach (var p in expected) cache.Record("c", "n", p.TimestampUnixNano, new Dictionary<string, double> { ["cpu"] = p.Value });
        int fetched = 0;
        Task<IReadOnlyList<LODPoint>> Fetch(DateTime a, DateTime b, CancellationToken ct)
        { fetched++; return Task.FromResult<IReadOnlyList<LODPoint>>(expected); }
        await cache.QueryAsync("c", "n", "remote", now.AddHours(-1), now, false, Fetch);
        var replay = await cache.QueryAsync("c", "n", "remote", now.AddHours(-1), now, false, Fetch);
        Assert.Equal(expected, replay);
        Assert.Equal(1, fetched);
        var usage = cache.GetUsage(60);
        Assert.True(usage.LiveZstdBytes > 0);
        Assert.True(usage.StoredZstdBytes > 0);
        Assert.True(usage.LiveBytes < expected.Length * 32);
        cache.ClearLive();
        Assert.Equal(0, cache.GetUsage(60).LiveZstdBytes);
        Assert.True(cache.GetUsage(60).StoredZstdBytes > 0);
        cache.ClearStored();
        Assert.Equal(0, cache.GetUsage(60).StoredZstdBytes);
    }

    [Fact]
    public void ResponseDecodeCountsRawAndZstdSeparatelyAndRejectsMalformedEnvelopes()
    {
        var original = new ListNodesResponse { CollectorName = new string('a', 2048) };
        var raw = original.ToByteArray();
        var zipped = ZstdCodec.CompressIfUseful(raw)!;
        var counter = new ClientPayloadCounter();
        var decoded = ClientResponseCompression.Decode(new ListNodesResponse
        { ZstdPayload = ByteString.CopyFrom(zipped), DecodedSize = (uint)raw.Length }, counter);
        Assert.Equal(original, decoded);
        ClientResponseCompression.Decode(new ListNodesResponse { CollectorName = "old" }, counter);
        var stats = counter.Snapshot();
        Assert.Equal(1, stats.CompressedMessages);
        Assert.Equal(2, stats.Messages);
        Assert.Equal(raw.Length, stats.Decoded);
        Assert.Equal(zipped.Length, stats.Encoded);
        Assert.Equal(5, stats.Raw);
        Assert.ThrowsAny<Exception>(() => ZstdCodec.Decode(zipped, raw.Length - 1));
        Assert.Throws<InvalidDataException>(() => ClientResponseCompression.Decode(new ListNodesResponse
        { ZstdPayload = ByteString.CopyFrom(zipped), DecodedSize = uint.MaxValue }, counter));
        Assert.Throws<InvalidDataException>(() => ClientResponseCompression.Decode(new ListNodesResponse
        { DecodedSize = 1 }, counter));
        var nested = new ListNodesResponse { ZstdPayload = ByteString.CopyFrom(zipped), DecodedSize = (uint)raw.Length, CollectorName = new string('b', 2048) }.ToByteArray();
        Assert.Throws<InvalidDataException>(() => ClientResponseCompression.Decode(new ListNodesResponse
        { ZstdPayload = ByteString.CopyFrom(ZstdCodec.CompressIfUseful(nested)!), DecodedSize = (uint)nested.Length }, counter));
    }
}
