// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: madtom/v1/config.proto

package madtomv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessTelemetryMode int32

const (
	ProcessTelemetryMode_PROCESS_MODE_DISABLED          ProcessTelemetryMode = 0 // Neither: No /proc scanning, no streaming, no storage
	ProcessTelemetryMode_PROCESS_MODE_LIVE_ONLY         ProcessTelemetryMode = 1 // Probed: Live 1Hz stream for UI, not stored in TSDB
	ProcessTelemetryMode_PROCESS_MODE_PROBED_AND_STORED ProcessTelemetryMode = 2 // Probed & Stored: Live stream + Top-N written to TSDB
)

// Enum value maps for ProcessTelemetryMode.
var (
	ProcessTelemetryMode_name = map[int32]string{
		0: "PROCESS_MODE_DISABLED",
		1: "PROCESS_MODE_LIVE_ONLY",
		2: "PROCESS_MODE_PROBED_AND_STORED",
	}
	ProcessTelemetryMode_value = map[string]int32{
		"PROCESS_MODE_DISABLED":          0,
		"PROCESS_MODE_LIVE_ONLY":         1,
		"PROCESS_MODE_PROBED_AND_STORED": 2,
	}
)

func (x ProcessTelemetryMode) Enum() *ProcessTelemetryMode {
	p := new(ProcessTelemetryMode)
	*p = x
	return p
}

func (x ProcessTelemetryMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessTelemetryMode) Descriptor() protoreflect.EnumDescriptor {
	return file_madtom_v1_config_proto_enumTypes[0].Descriptor()
}

func (ProcessTelemetryMode) Type() protoreflect.EnumType {
	return &file_madtom_v1_config_proto_enumTypes[0]
}

func (x ProcessTelemetryMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessTelemetryMode.Descriptor instead.
func (ProcessTelemetryMode) EnumDescriptor() ([]byte, []int) {
	return file_madtom_v1_config_proto_rawDescGZIP(), []int{0}
}

type GetNodeConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeConfigRequest) Reset() {
	*x = GetNodeConfigRequest{}
	mi := &file_madtom_v1_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeConfigRequest) ProtoMessage() {}

func (x *GetNodeConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_madtom_v1_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeConfigRequest.ProtoReflect.Descriptor instead.
func (*GetNodeConfigRequest) Descriptor() ([]byte, []int) {
	return file_madtom_v1_config_proto_rawDescGZIP(), []int{0}
}

func (x *GetNodeConfigRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type UpdateNodeConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Config        *NodeConfig            `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNodeConfigRequest) Reset() {
	*x = UpdateNodeConfigRequest{}
	mi := &file_madtom_v1_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNodeConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeConfigRequest) ProtoMessage() {}

func (x *UpdateNodeConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_madtom_v1_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateNodeConfigRequest) Descriptor() ([]byte, []int) {
	return file_madtom_v1_config_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateNodeConfigRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *UpdateNodeConfigRequest) GetConfig() *NodeConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// NodeConfig controls what the daemon measures and what the collector retains.
type NodeConfig struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Opt-in Collection Switches (Daemon Level)
	CollectCpuOverall         bool `protobuf:"varint,2,opt,name=collect_cpu_overall,json=collectCpuOverall,proto3" json:"collect_cpu_overall,omitempty"`
	CollectCpuPerCore         bool `protobuf:"varint,3,opt,name=collect_cpu_per_core,json=collectCpuPerCore,proto3" json:"collect_cpu_per_core,omitempty"`
	CollectMemoryBasic        bool `protobuf:"varint,4,opt,name=collect_memory_basic,json=collectMemoryBasic,proto3" json:"collect_memory_basic,omitempty"`
	CollectMemorySwapZram     bool `protobuf:"varint,5,opt,name=collect_memory_swap_zram,json=collectMemorySwapZram,proto3" json:"collect_memory_swap_zram,omitempty"`
	CollectPowerBattery       bool `protobuf:"varint,6,opt,name=collect_power_battery,json=collectPowerBattery,proto3" json:"collect_power_battery,omitempty"`
	CollectNetworkInterfaces  bool `protobuf:"varint,7,opt,name=collect_network_interfaces,json=collectNetworkInterfaces,proto3" json:"collect_network_interfaces,omitempty"`
	CollectNetworkConnections bool `protobuf:"varint,8,opt,name=collect_network_connections,json=collectNetworkConnections,proto3" json:"collect_network_connections,omitempty"`
	// Polling cadences (milliseconds)
	FastPollIntervalMs   uint32 `protobuf:"varint,9,opt,name=fast_poll_interval_ms,json=fastPollIntervalMs,proto3" json:"fast_poll_interval_ms,omitempty"`        // Default 1000ms (1s)
	NormalPollIntervalMs uint32 `protobuf:"varint,10,opt,name=normal_poll_interval_ms,json=normalPollIntervalMs,proto3" json:"normal_poll_interval_ms,omitempty"` // Default 10000ms (10s)
	SlowPollIntervalMs   uint32 `protobuf:"varint,11,opt,name=slow_poll_interval_ms,json=slowPollIntervalMs,proto3" json:"slow_poll_interval_ms,omitempty"`       // Default 30000ms (30s)
	// Spooling & Compression
	EnableZstdCompression   bool   `protobuf:"varint,12,opt,name=enable_zstd_compression,json=enableZstdCompression,proto3" json:"enable_zstd_compression,omitempty"`
	TwampTarget             string `protobuf:"bytes,14,opt,name=twamp_target,json=twampTarget,proto3" json:"twamp_target,omitempty"`                                        // TWAMP Light UDP reflector host:port; empty disables probes
	TwampClocksSynchronized bool   `protobuf:"varint,15,opt,name=twamp_clocks_synchronized,json=twampClocksSynchronized,proto3" json:"twamp_clocks_synchronized,omitempty"` // Operator assertion; reflector must also set its S bit
	MaxSpoolBytes           uint64 `protobuf:"varint,13,opt,name=max_spool_bytes,json=maxSpoolBytes,proto3" json:"max_spool_bytes,omitempty"`                               // Default 1,073,741,824 (1 GB)
	// Process Telemetry Mode & Top-N Count
	ProcessMode   ProcessTelemetryMode `protobuf:"varint,16,opt,name=process_mode,json=processMode,proto3,enum=madtom.v1.ProcessTelemetryMode" json:"process_mode,omitempty"`
	TopNProcesses uint32               `protobuf:"varint,17,opt,name=top_n_processes,json=topNProcesses,proto3" json:"top_n_processes,omitempty"` // Top N processes (1 to 10, default 5)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeConfig) Reset() {
	*x = NodeConfig{}
	mi := &file_madtom_v1_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeConfig) ProtoMessage() {}

func (x *NodeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_madtom_v1_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeConfig.ProtoReflect.Descriptor instead.
func (*NodeConfig) Descriptor() ([]byte, []int) {
	return file_madtom_v1_config_proto_rawDescGZIP(), []int{2}
}

func (x *NodeConfig) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeConfig) GetCollectCpuOverall() bool {
	if x != nil {
		return x.CollectCpuOverall
	}
	return false
}

func (x *NodeConfig) GetCollectCpuPerCore() bool {
	if x != nil {
		return x.CollectCpuPerCore
	}
	return false
}

func (x *NodeConfig) GetCollectMemoryBasic() bool {
	if x != nil {
		return x.CollectMemoryBasic
	}
	return false
}

func (x *NodeConfig) GetCollectMemorySwapZram() bool {
	if x != nil {
		return x.CollectMemorySwapZram
	}
	return false
}

func (x *NodeConfig) GetCollectPowerBattery() bool {
	if x != nil {
		return x.CollectPowerBattery
	}
	return false
}

func (x *NodeConfig) GetCollectNetworkInterfaces() bool {
	if x != nil {
		return x.CollectNetworkInterfaces
	}
	return false
}

func (x *NodeConfig) GetCollectNetworkConnections() bool {
	if x != nil {
		return x.CollectNetworkConnections
	}
	return false
}

func (x *NodeConfig) GetFastPollIntervalMs() uint32 {
	if x != nil {
		return x.FastPollIntervalMs
	}
	return 0
}

func (x *NodeConfig) GetNormalPollIntervalMs() uint32 {
	if x != nil {
		return x.NormalPollIntervalMs
	}
	return 0
}

func (x *NodeConfig) GetSlowPollIntervalMs() uint32 {
	if x != nil {
		return x.SlowPollIntervalMs
	}
	return 0
}

func (x *NodeConfig) GetEnableZstdCompression() bool {
	if x != nil {
		return x.EnableZstdCompression
	}
	return false
}

func (x *NodeConfig) GetTwampTarget() string {
	if x != nil {
		return x.TwampTarget
	}
	return ""
}

func (x *NodeConfig) GetTwampClocksSynchronized() bool {
	if x != nil {
		return x.TwampClocksSynchronized
	}
	return false
}

func (x *NodeConfig) GetMaxSpoolBytes() uint64 {
	if x != nil {
		return x.MaxSpoolBytes
	}
	return 0
}

func (x *NodeConfig) GetProcessMode() ProcessTelemetryMode {
	if x != nil {
		return x.ProcessMode
	}
	return ProcessTelemetryMode_PROCESS_MODE_DISABLED
}

func (x *NodeConfig) GetTopNProcesses() uint32 {
	if x != nil {
		return x.TopNProcesses
	}
	return 0
}

type ConfigAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigAck) Reset() {
	*x = ConfigAck{}
	mi := &file_madtom_v1_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigAck) ProtoMessage() {}

func (x *ConfigAck) ProtoReflect() protoreflect.Message {
	mi := &file_madtom_v1_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigAck.ProtoReflect.Descriptor instead.
func (*ConfigAck) Descriptor() ([]byte, []int) {
	return file_madtom_v1_config_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_madtom_v1_config_proto protoreflect.FileDescriptor

const file_madtom_v1_config_proto_rawDesc = "" +
	"\n" +
	"\x16madtom/v1/config.proto\x12\tmadtom.v1\"/\n" +
	"\x14GetNodeConfigRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"a\n" +
	"\x17UpdateNodeConfigRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12-\n" +
	"\x06config\x18\x02 \x01(\v2\x15.madtom.v1.NodeConfigR\x06config\"\xeb\x06\n" +
	"\n" +
	"NodeConfig\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12.\n" +
	"\x13collect_cpu_overall\x18\x02 \x01(\bR\x11collectCpuOverall\x12/\n" +
	"\x14collect_cpu_per_core\x18\x03 \x01(\bR\x11collectCpuPerCore\x120\n" +
	"\x14collect_memory_basic\x18\x04 \x01(\bR\x12collectMemoryBasic\x127\n" +
	"\x18collect_memory_swap_zram\x18\x05 \x01(\bR\x15collectMemorySwapZram\x122\n" +
	"\x15collect_power_battery\x18\x06 \x01(\bR\x13collectPowerBattery\x12<\n" +
	"\x1acollect_network_interfaces\x18\a \x01(\bR\x18collectNetworkInterfaces\x12>\n" +
	"\x1bcollect_network_connections\x18\b \x01(\bR\x19collectNetworkConnections\x121\n" +
	"\x15fast_poll_interval_ms\x18\t \x01(\rR\x12fastPollIntervalMs\x125\n" +
	"\x17normal_poll_interval_ms\x18\n" +
	" \x01(\rR\x14normalPollIntervalMs\x121\n" +
	"\x15slow_poll_interval_ms\x18\v \x01(\rR\x12slowPollIntervalMs\x126\n" +
	"\x17enable_zstd_compression\x18\f \x01(\bR\x15enableZstdCompression\x12!\n" +
	"\ftwamp_target\x18\x0e \x01(\tR\vtwampTarget\x12:\n" +
	"\x19twamp_clocks_synchronized\x18\x0f \x01(\bR\x17twampClocksSynchronized\x12&\n" +
	"\x0fmax_spool_bytes\x18\r \x01(\x04R\rmaxSpoolBytes\x12B\n" +
	"\fprocess_mode\x18\x10 \x01(\x0e2\x1f.madtom.v1.ProcessTelemetryModeR\vprocessMode\x12&\n" +
	"\x0ftop_n_processes\x18\x11 \x01(\rR\rtopNProcesses\"?\n" +
	"\tConfigAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*q\n" +
	"\x14ProcessTelemetryMode\x12\x19\n" +
	"\x15PROCESS_MODE_DISABLED\x10\x00\x12\x1a\n" +
	"\x16PROCESS_MODE_LIVE_ONLY\x10\x01\x12\"\n" +
	"\x1ePROCESS_MODE_PROBED_AND_STORED\x10\x022\xa6\x01\n" +
	"\rConfigService\x12G\n" +
	"\rGetNodeConfig\x12\x1f.madtom.v1.GetNodeConfigRequest\x1a\x15.madtom.v1.NodeConfig\x12L\n" +
	"\x10UpdateNodeConfig\x12\".madtom.v1.UpdateNodeConfigRequest\x1a\x14.madtom.v1.ConfigAckBYZ3github.com/DarkDuck007/madtom/pkg/proto/v1;madtomv1\xaa\x02!MADTOM.Plugins.Telemetry.Proto.V1b\x06proto3"

var (
	file_madtom_v1_config_proto_rawDescOnce sync.Once
	file_madtom_v1_config_proto_rawDescData []byte
)

func file_madtom_v1_config_proto_rawDescGZIP() []byte {
	file_madtom_v1_config_proto_rawDescOnce.Do(func() {
		file_madtom_v1_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_madtom_v1_config_proto_rawDesc), len(file_madtom_v1_config_proto_rawDesc)))
	})
	return file_madtom_v1_config_proto_rawDescData
}

var file_madtom_v1_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_madtom_v1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_madtom_v1_config_proto_goTypes = []any{
	(ProcessTelemetryMode)(0),       // 0: madtom.v1.ProcessTelemetryMode
	(*GetNodeConfigRequest)(nil),    // 1: madtom.v1.GetNodeConfigRequest
	(*UpdateNodeConfigRequest)(nil), // 2: madtom.v1.UpdateNodeConfigRequest
	(*NodeConfig)(nil),              // 3: madtom.v1.NodeConfig
	(*ConfigAck)(nil),               // 4: madtom.v1.ConfigAck
}
var file_madtom_v1_config_proto_depIdxs = []int32{
	3, // 0: madtom.v1.UpdateNodeConfigRequest.config:type_name -> madtom.v1.NodeConfig
	0, // 1: madtom.v1.NodeConfig.process_mode:type_name -> madtom.v1.ProcessTelemetryMode
	1, // 2: madtom.v1.ConfigService.GetNodeConfig:input_type -> madtom.v1.GetNodeConfigRequest
	2, // 3: madtom.v1.ConfigService.UpdateNodeConfig:input_type -> madtom.v1.UpdateNodeConfigRequest
	3, // 4: madtom.v1.ConfigService.GetNodeConfig:output_type -> madtom.v1.NodeConfig
	4, // 5: madtom.v1.ConfigService.UpdateNodeConfig:output_type -> madtom.v1.ConfigAck
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_madtom_v1_config_proto_init() }
func file_madtom_v1_config_proto_init() {
	if File_madtom_v1_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_madtom_v1_config_proto_rawDesc), len(file_madtom_v1_config_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_madtom_v1_config_proto_goTypes,
		DependencyIndexes: file_madtom_v1_config_proto_depIdxs,
		EnumInfos:         file_madtom_v1_config_proto_enumTypes,
		MessageInfos:      file_madtom_v1_config_proto_msgTypes,
	}.Build()
	File_madtom_v1_config_proto = out.File
	file_madtom_v1_config_proto_goTypes = nil
	file_madtom_v1_config_proto_depIdxs = nil
}
