// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: madtom/v1/ingest.proto

package madtomv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TelemetryBatch represents a slice of telemetry records, either live or drained from WAL spool.
type TelemetryBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	SequenceId    int64                  `protobuf:"varint,2,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`
	SegmentId     string                 `protobuf:"bytes,3,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`              // File identifier e.g. "segment-00001.wal"
	SegmentOffset int64                  `protobuf:"varint,4,opt,name=segment_offset,json=segmentOffset,proto3" json:"segment_offset,omitempty"` // End byte offset within the segment file
	IsBacklog     bool                   `protobuf:"varint,5,opt,name=is_backlog,json=isBacklog,proto3" json:"is_backlog,omitempty"`             // True if flushed from offline storage
	Samples       []*SystemMetrics       `protobuf:"bytes,6,rep,name=samples,proto3" json:"samples,omitempty"`
	// Optional compressed payload (e.g. zstd)
	IsCompressed      bool   `protobuf:"varint,7,opt,name=is_compressed,json=isCompressed,proto3" json:"is_compressed,omitempty"`
	CompressedPayload []byte `protobuf:"bytes,8,opt,name=compressed_payload,json=compressedPayload,proto3" json:"compressed_payload,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TelemetryBatch) Reset() {
	*x = TelemetryBatch{}
	mi := &file_madtom_v1_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryBatch) ProtoMessage() {}

func (x *TelemetryBatch) ProtoReflect() protoreflect.Message {
	mi := &file_madtom_v1_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryBatch.ProtoReflect.Descriptor instead.
func (*TelemetryBatch) Descriptor() ([]byte, []int) {
	return file_madtom_v1_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryBatch) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *TelemetryBatch) GetSequenceId() int64 {
	if x != nil {
		return x.SequenceId
	}
	return 0
}

func (x *TelemetryBatch) GetSegmentId() string {
	if x != nil {
		return x.SegmentId
	}
	return ""
}

func (x *TelemetryBatch) GetSegmentOffset() int64 {
	if x != nil {
		return x.SegmentOffset
	}
	return 0
}

func (x *TelemetryBatch) GetIsBacklog() bool {
	if x != nil {
		return x.IsBacklog
	}
	return false
}

func (x *TelemetryBatch) GetSamples() []*SystemMetrics {
	if x != nil {
		return x.Samples
	}
	return nil
}

func (x *TelemetryBatch) GetIsCompressed() bool {
	if x != nil {
		return x.IsCompressed
	}
	return false
}

func (x *TelemetryBatch) GetCompressedPayload() []byte {
	if x != nil {
		return x.CompressedPayload
	}
	return nil
}

// BatchAck signals receipt and successful persistence of a segment batch.
type BatchAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	SegmentId     string                 `protobuf:"bytes,2,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	SegmentOffset int64                  `protobuf:"varint,3,opt,name=segment_offset,json=segmentOffset,proto3" json:"segment_offset,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Config        *NodeConfig            `protobuf:"bytes,6,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchAck) Reset() {
	*x = BatchAck{}
	mi := &file_madtom_v1_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAck) ProtoMessage() {}

func (x *BatchAck) ProtoReflect() protoreflect.Message {
	mi := &file_madtom_v1_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAck.ProtoReflect.Descriptor instead.
func (*BatchAck) Descriptor() ([]byte, []int) {
	return file_madtom_v1_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *BatchAck) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *BatchAck) GetSegmentId() string {
	if x != nil {
		return x.SegmentId
	}
	return ""
}

func (x *BatchAck) GetSegmentOffset() int64 {
	if x != nil {
		return x.SegmentOffset
	}
	return 0
}

func (x *BatchAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BatchAck) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *BatchAck) GetConfig() *NodeConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// PollRequest queries a pull-mode daemon for buffered samples since last ACK.
type PollRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NodeId             string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	LastAckedSegmentId string                 `protobuf:"bytes,2,opt,name=last_acked_segment_id,json=lastAckedSegmentId,proto3" json:"last_acked_segment_id,omitempty"`
	LastAckedOffset    int64                  `protobuf:"varint,3,opt,name=last_acked_offset,json=lastAckedOffset,proto3" json:"last_acked_offset,omitempty"`
	MaxSamples         uint32                 `protobuf:"varint,4,opt,name=max_samples,json=maxSamples,proto3" json:"max_samples,omitempty"`
	Config             *NodeConfig            `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PollRequest) Reset() {
	*x = PollRequest{}
	mi := &file_madtom_v1_ingest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollRequest) ProtoMessage() {}

func (x *PollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_madtom_v1_ingest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollRequest.ProtoReflect.Descriptor instead.
func (*PollRequest) Descriptor() ([]byte, []int) {
	return file_madtom_v1_ingest_proto_rawDescGZIP(), []int{2}
}

func (x *PollRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PollRequest) GetLastAckedSegmentId() string {
	if x != nil {
		return x.LastAckedSegmentId
	}
	return ""
}

func (x *PollRequest) GetLastAckedOffset() int64 {
	if x != nil {
		return x.LastAckedOffset
	}
	return 0
}

func (x *PollRequest) GetMaxSamples() uint32 {
	if x != nil {
		return x.MaxSamples
	}
	return 0
}

func (x *PollRequest) GetConfig() *NodeConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

var File_madtom_v1_ingest_proto protoreflect.FileDescriptor

const file_madtom_v1_ingest_proto_rawDesc = "" +
	"\n" +
	"\x16madtom/v1/ingest.proto\x12\tmadtom.v1\x1a\x17madtom/v1/metrics.proto\x1a\x16madtom/v1/config.proto\"\xb7\x02\n" +
	"\x0eTelemetryBatch\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vsequence_id\x18\x02 \x01(\x03R\n" +
	"sequenceId\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x03 \x01(\tR\tsegmentId\x12%\n" +
	"\x0esegment_offset\x18\x04 \x01(\x03R\rsegmentOffset\x12\x1d\n" +
	"\n" +
	"is_backlog\x18\x05 \x01(\bR\tisBacklog\x122\n" +
	"\asamples\x18\x06 \x03(\v2\x18.madtom.v1.SystemMetricsR\asamples\x12#\n" +
	"\ris_compressed\x18\a \x01(\bR\fisCompressed\x12-\n" +
	"\x12compressed_payload\x18\b \x01(\fR\x11compressedPayload\"\xd7\x01\n" +
	"\bBatchAck\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x02 \x01(\tR\tsegmentId\x12%\n" +
	"\x0esegment_offset\x18\x03 \x01(\x03R\rsegmentOffset\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12-\n" +
	"\x06config\x18\x06 \x01(\v2\x15.madtom.v1.NodeConfigR\x06config\"\xd5\x01\n" +
	"\vPollRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x121\n" +
	"\x15last_acked_segment_id\x18\x02 \x01(\tR\x12lastAckedSegmentId\x12*\n" +
	"\x11last_acked_offset\x18\x03 \x01(\x03R\x0flastAckedOffset\x12\x1f\n" +
	"\vmax_samples\x18\x04 \x01(\rR\n" +
	"maxSamples\x12-\n" +
	"\x06config\x18\x05 \x01(\v2\x15.madtom.v1.NodeConfigR\x06config2\xe4\x01\n" +
	"\rIngestService\x12E\n" +
	"\x0fPushBatchStream\x12\x19.madtom.v1.TelemetryBatch\x1a\x13.madtom.v1.BatchAck(\x010\x01\x12B\n" +
	"\rPollTelemetry\x12\x16.madtom.v1.PollRequest\x1a\x19.madtom.v1.TelemetryBatch\x12H\n" +
	"\x12ReceiveBatchStream\x12\x13.madtom.v1.BatchAck\x1a\x19.madtom.v1.TelemetryBatch(\x010\x01BYZ3github.com/DarkDuck007/madtom/pkg/proto/v1;madtomv1\xaa\x02!MADTOM.Plugins.Telemetry.Proto.V1b\x06proto3"

var (
	file_madtom_v1_ingest_proto_rawDescOnce sync.Once
	file_madtom_v1_ingest_proto_rawDescData []byte
)

func file_madtom_v1_ingest_proto_rawDescGZIP() []byte {
	file_madtom_v1_ingest_proto_rawDescOnce.Do(func() {
		file_madtom_v1_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_madtom_v1_ingest_proto_rawDesc), len(file_madtom_v1_ingest_proto_rawDesc)))
	})
	return file_madtom_v1_ingest_proto_rawDescData
}

var file_madtom_v1_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_madtom_v1_ingest_proto_goTypes = []any{
	(*TelemetryBatch)(nil), // 0: madtom.v1.TelemetryBatch
	(*BatchAck)(nil),       // 1: madtom.v1.BatchAck
	(*PollRequest)(nil),    // 2: madtom.v1.PollRequest
	(*SystemMetrics)(nil),  // 3: madtom.v1.SystemMetrics
	(*NodeConfig)(nil),     // 4: madtom.v1.NodeConfig
}
var file_madtom_v1_ingest_proto_depIdxs = []int32{
	3, // 0: madtom.v1.TelemetryBatch.samples:type_name -> madtom.v1.SystemMetrics
	4, // 1: madtom.v1.BatchAck.config:type_name -> madtom.v1.NodeConfig
	4, // 2: madtom.v1.PollRequest.config:type_name -> madtom.v1.NodeConfig
	0, // 3: madtom.v1.IngestService.PushBatchStream:input_type -> madtom.v1.TelemetryBatch
	2, // 4: madtom.v1.IngestService.PollTelemetry:input_type -> madtom.v1.PollRequest
	1, // 5: madtom.v1.IngestService.ReceiveBatchStream:input_type -> madtom.v1.BatchAck
	1, // 6: madtom.v1.IngestService.PushBatchStream:output_type -> madtom.v1.BatchAck
	0, // 7: madtom.v1.IngestService.PollTelemetry:output_type -> madtom.v1.TelemetryBatch
	0, // 8: madtom.v1.IngestService.ReceiveBatchStream:output_type -> madtom.v1.TelemetryBatch
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_madtom_v1_ingest_proto_init() }
func file_madtom_v1_ingest_proto_init() {
	if File_madtom_v1_ingest_proto != nil {
		return
	}
	file_madtom_v1_metrics_proto_init()
	file_madtom_v1_config_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_madtom_v1_ingest_proto_rawDesc), len(file_madtom_v1_ingest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_madtom_v1_ingest_proto_goTypes,
		DependencyIndexes: file_madtom_v1_ingest_proto_depIdxs,
		MessageInfos:      file_madtom_v1_ingest_proto_msgTypes,
	}.Build()
	File_madtom_v1_ingest_proto = out.File
	file_madtom_v1_ingest_proto_goTypes = nil
	file_madtom_v1_ingest_proto_depIdxs = nil
}
