// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: madtom/v1/ingest.proto

package madtomv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IngestService_PushBatchStream_FullMethodName    = "/madtom.v1.IngestService/PushBatchStream"
	IngestService_PollTelemetry_FullMethodName      = "/madtom.v1.IngestService/PollTelemetry"
	IngestService_ReceiveBatchStream_FullMethodName = "/madtom.v1.IngestService/ReceiveBatchStream"
)

// IngestServiceClient is the client API for IngestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IngestService coordinates data intake between Monitored Node Daemons and Collectors.
type IngestServiceClient interface {
	// Mode A: Push - Daemon maintains an outbound stream pushing batches and receiving segment ACKs.
	PushBatchStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TelemetryBatch, BatchAck], error)
	// Mode B: Pull - Collector periodically scrapes the daemon for pending metrics.
	PollTelemetry(ctx context.Context, in *PollRequest, opts ...grpc.CallOption) (*TelemetryBatch, error)
	// Collector connects to a listening daemon; daemon sends at its own cadence.
	ReceiveBatchStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BatchAck, TelemetryBatch], error)
}

type ingestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIngestServiceClient(cc grpc.ClientConnInterface) IngestServiceClient {
	return &ingestServiceClient{cc}
}

func (c *ingestServiceClient) PushBatchStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TelemetryBatch, BatchAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IngestService_ServiceDesc.Streams[0], IngestService_PushBatchStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TelemetryBatch, BatchAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngestService_PushBatchStreamClient = grpc.BidiStreamingClient[TelemetryBatch, BatchAck]

func (c *ingestServiceClient) PollTelemetry(ctx context.Context, in *PollRequest, opts ...grpc.CallOption) (*TelemetryBatch, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TelemetryBatch)
	err := c.cc.Invoke(ctx, IngestService_PollTelemetry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingestServiceClient) ReceiveBatchStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BatchAck, TelemetryBatch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IngestService_ServiceDesc.Streams[1], IngestService_ReceiveBatchStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BatchAck, TelemetryBatch]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngestService_ReceiveBatchStreamClient = grpc.BidiStreamingClient[BatchAck, TelemetryBatch]

// IngestServiceServer is the server API for IngestService service.
// All implementations must embed UnimplementedIngestServiceServer
// for forward compatibility.
//
// IngestService coordinates data intake between Monitored Node Daemons and Collectors.
type IngestServiceServer interface {
	// Mode A: Push - Daemon maintains an outbound stream pushing batches and receiving segment ACKs.
	PushBatchStream(grpc.BidiStreamingServer[TelemetryBatch, BatchAck]) error
	// Mode B: Pull - Collector periodically scrapes the daemon for pending metrics.
	PollTelemetry(context.Context, *PollRequest) (*TelemetryBatch, error)
	// Collector connects to a listening daemon; daemon sends at its own cadence.
	ReceiveBatchStream(grpc.BidiStreamingServer[BatchAck, TelemetryBatch]) error
	mustEmbedUnimplementedIngestServiceServer()
}

// UnimplementedIngestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIngestServiceServer struct{}

func (UnimplementedIngestServiceServer) PushBatchStream(grpc.BidiStreamingServer[TelemetryBatch, BatchAck]) error {
	return status.Error(codes.Unimplemented, "method PushBatchStream not implemented")
}
func (UnimplementedIngestServiceServer) PollTelemetry(context.Context, *PollRequest) (*TelemetryBatch, error) {
	return nil, status.Error(codes.Unimplemented, "method PollTelemetry not implemented")
}
func (UnimplementedIngestServiceServer) ReceiveBatchStream(grpc.BidiStreamingServer[BatchAck, TelemetryBatch]) error {
	return status.Error(codes.Unimplemented, "method ReceiveBatchStream not implemented")
}
func (UnimplementedIngestServiceServer) mustEmbedUnimplementedIngestServiceServer() {}
func (UnimplementedIngestServiceServer) testEmbeddedByValue()                       {}

// UnsafeIngestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IngestServiceServer will
// result in compilation errors.
type UnsafeIngestServiceServer interface {
	mustEmbedUnimplementedIngestServiceServer()
}

func RegisterIngestServiceServer(s grpc.ServiceRegistrar, srv IngestServiceServer) {
	// If the following call panics, it indicates UnimplementedIngestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IngestService_ServiceDesc, srv)
}

func _IngestService_PushBatchStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IngestServiceServer).PushBatchStream(&grpc.GenericServerStream[TelemetryBatch, BatchAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngestService_PushBatchStreamServer = grpc.BidiStreamingServer[TelemetryBatch, BatchAck]

func _IngestService_PollTelemetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestServiceServer).PollTelemetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IngestService_PollTelemetry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestServiceServer).PollTelemetry(ctx, req.(*PollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IngestService_ReceiveBatchStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IngestServiceServer).ReceiveBatchStream(&grpc.GenericServerStream[BatchAck, TelemetryBatch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngestService_ReceiveBatchStreamServer = grpc.BidiStreamingServer[BatchAck, TelemetryBatch]

// IngestService_ServiceDesc is the grpc.ServiceDesc for IngestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IngestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "madtom.v1.IngestService",
	HandlerType: (*IngestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PollTelemetry",
			Handler:    _IngestService_PollTelemetry_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PushBatchStream",
			Handler:       _IngestService_PushBatchStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ReceiveBatchStream",
			Handler:       _IngestService_ReceiveBatchStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "madtom/v1/ingest.proto",
}
