// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: madtom/v1/logs.proto

package madtomv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Individual system log entry captured from systemd journal / syslog.
type LogRecord struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Seq               uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`                                                                                // Monotonic per-node sequence number
	TimestampUnixNano int64                  `protobuf:"varint,2,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`                         // __REALTIME_TIMESTAMP
	Priority          uint32                 `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`                                                                      // syslog PRIORITY (0=emerg..7=debug)
	Unit              string                 `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit,omitempty"`                                                                               // _SYSTEMD_UNIT or SYSLOG_IDENTIFIER
	Message           string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`                                                                         // MESSAGE
	Fields            map[string]string      `protobuf:"bytes,6,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional selected journal fields (_PID, _COMM, etc.)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LogRecord) Reset() {
	*x = LogRecord{}
	mi := &file_madtom_v1_logs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRecord) ProtoMessage() {}

func (x *LogRecord) ProtoReflect() protoreflect.Message {
	mi := &file_madtom_v1_logs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRecord.ProtoReflect.Descriptor instead.
func (*LogRecord) Descriptor() ([]byte, []int) {
	return file_madtom_v1_logs_proto_rawDescGZIP(), []int{0}
}

func (x *LogRecord) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *LogRecord) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

func (x *LogRecord) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *LogRecord) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *LogRecord) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogRecord) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

// Wrapper for batch serialization before zstd compression.
type LogRecordList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*LogRecord           `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRecordList) Reset() {
	*x = LogRecordList{}
	mi := &file_madtom_v1_logs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRecordList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRecordList) ProtoMessage() {}

func (x *LogRecordList) ProtoReflect() protoreflect.Message {
	mi := &file_madtom_v1_logs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRecordList.ProtoReflect.Descriptor instead.
func (*LogRecordList) Descriptor() ([]byte, []int) {
	return file_madtom_v1_logs_proto_rawDescGZIP(), []int{1}
}

func (x *LogRecordList) GetRecords() []*LogRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

// LogChunk is a self-contained, zstd-compressed block of log records (typically 256 records).
// Kept compressed during transit, in collector Pebble store, and in client LRU cache.
type LogChunk struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ChunkId         uint64                 `protobuf:"varint,2,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`    // chunk index = first_seq / 256
	FirstSeq        uint64                 `protobuf:"varint,3,opt,name=first_seq,json=firstSeq,proto3" json:"first_seq,omitempty"` // first sequence number in this chunk
	LastSeq         uint64                 `protobuf:"varint,4,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`    // last sequence number in this chunk
	FirstTsUnixNano int64                  `protobuf:"varint,5,opt,name=first_ts_unix_nano,json=firstTsUnixNano,proto3" json:"first_ts_unix_nano,omitempty"`
	LastTsUnixNano  int64                  `protobuf:"varint,6,opt,name=last_ts_unix_nano,json=lastTsUnixNano,proto3" json:"last_ts_unix_nano,omitempty"`
	RecordCount     uint32                 `protobuf:"varint,7,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	Sealed          bool                   `protobuf:"varint,8,opt,name=sealed,proto3" json:"sealed,omitempty"`                             // true if chunk reached 256 records or closed
	ZstdRecords     []byte                 `protobuf:"bytes,9,opt,name=zstd_records,json=zstdRecords,proto3" json:"zstd_records,omitempty"` // compressed protobuf bytes of LogRecordList
	RawSize         uint32                 `protobuf:"varint,10,opt,name=raw_size,json=rawSize,proto3" json:"raw_size,omitempty"`           // uncompressed byte size of LogRecordList
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LogChunk) Reset() {
	*x = LogChunk{}
	mi := &file_madtom_v1_logs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogChunk) ProtoMessage() {}

func (x *LogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_madtom_v1_logs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogChunk.ProtoReflect.Descriptor instead.
func (*LogChunk) Descriptor() ([]byte, []int) {
	return file_madtom_v1_logs_proto_rawDescGZIP(), []int{2}
}

func (x *LogChunk) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *LogChunk) GetChunkId() uint64 {
	if x != nil {
		return x.ChunkId
	}
	return 0
}

func (x *LogChunk) GetFirstSeq() uint64 {
	if x != nil {
		return x.FirstSeq
	}
	return 0
}

func (x *LogChunk) GetLastSeq() uint64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

func (x *LogChunk) GetFirstTsUnixNano() int64 {
	if x != nil {
		return x.FirstTsUnixNano
	}
	return 0
}

func (x *LogChunk) GetLastTsUnixNano() int64 {
	if x != nil {
		return x.LastTsUnixNano
	}
	return 0
}

func (x *LogChunk) GetRecordCount() uint32 {
	if x != nil {
		return x.RecordCount
	}
	return 0
}

func (x *LogChunk) GetSealed() bool {
	if x != nil {
		return x.Sealed
	}
	return false
}

func (x *LogChunk) GetZstdRecords() []byte {
	if x != nil {
		return x.ZstdRecords
	}
	return nil
}

func (x *LogChunk) GetRawSize() uint32 {
	if x != nil {
		return x.RawSize
	}
	return 0
}

var File_madtom_v1_logs_proto protoreflect.FileDescriptor

const file_madtom_v1_logs_proto_rawDesc = "" +
	"\n" +
	"\x14madtom/v1/logs.proto\x12\tmadtom.v1\"\x8c\x02\n" +
	"\tLogRecord\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12.\n" +
	"\x13timestamp_unix_nano\x18\x02 \x01(\x03R\x11timestampUnixNano\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\rR\bpriority\x12\x12\n" +
	"\x04unit\x18\x04 \x01(\tR\x04unit\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x128\n" +
	"\x06fields\x18\x06 \x03(\v2 .madtom.v1.LogRecord.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"?\n" +
	"\rLogRecordList\x12.\n" +
	"\arecords\x18\x01 \x03(\v2\x14.madtom.v1.LogRecordR\arecords\"\xc7\x02\n" +
	"\bLogChunk\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x19\n" +
	"\bchunk_id\x18\x02 \x01(\x04R\achunkId\x12\x1b\n" +
	"\tfirst_seq\x18\x03 \x01(\x04R\bfirstSeq\x12\x19\n" +
	"\blast_seq\x18\x04 \x01(\x04R\alastSeq\x12+\n" +
	"\x12first_ts_unix_nano\x18\x05 \x01(\x03R\x0ffirstTsUnixNano\x12)\n" +
	"\x11last_ts_unix_nano\x18\x06 \x01(\x03R\x0elastTsUnixNano\x12!\n" +
	"\frecord_count\x18\a \x01(\rR\vrecordCount\x12\x16\n" +
	"\x06sealed\x18\b \x01(\bR\x06sealed\x12!\n" +
	"\fzstd_records\x18\t \x01(\fR\vzstdRecords\x12\x19\n" +
	"\braw_size\x18\n" +
	" \x01(\rR\arawSizeBYZ3github.com/DarkDuck007/madtom/pkg/proto/v1;madtomv1\xaa\x02!MADTOM.Plugins.Telemetry.Proto.V1b\x06proto3"

var (
	file_madtom_v1_logs_proto_rawDescOnce sync.Once
	file_madtom_v1_logs_proto_rawDescData []byte
)

func file_madtom_v1_logs_proto_rawDescGZIP() []byte {
	file_madtom_v1_logs_proto_rawDescOnce.Do(func() {
		file_madtom_v1_logs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_madtom_v1_logs_proto_rawDesc), len(file_madtom_v1_logs_proto_rawDesc)))
	})
	return file_madtom_v1_logs_proto_rawDescData
}

var file_madtom_v1_logs_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_madtom_v1_logs_proto_goTypes = []any{
	(*LogRecord)(nil),     // 0: madtom.v1.LogRecord
	(*LogRecordList)(nil), // 1: madtom.v1.LogRecordList
	(*LogChunk)(nil),      // 2: madtom.v1.LogChunk
	nil,                   // 3: madtom.v1.LogRecord.FieldsEntry
}
var file_madtom_v1_logs_proto_depIdxs = []int32{
	3, // 0: madtom.v1.LogRecord.fields:type_name -> madtom.v1.LogRecord.FieldsEntry
	0, // 1: madtom.v1.LogRecordList.records:type_name -> madtom.v1.LogRecord
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_madtom_v1_logs_proto_init() }
func file_madtom_v1_logs_proto_init() {
	if File_madtom_v1_logs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_madtom_v1_logs_proto_rawDesc), len(file_madtom_v1_logs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_madtom_v1_logs_proto_goTypes,
		DependencyIndexes: file_madtom_v1_logs_proto_depIdxs,
		MessageInfos:      file_madtom_v1_logs_proto_msgTypes,
	}.Build()
	File_madtom_v1_logs_proto = out.File
	file_madtom_v1_logs_proto_goTypes = nil
	file_madtom_v1_logs_proto_depIdxs = nil
}
