// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: madtom/v1/metrics.proto

package madtomv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SystemMetrics represents a point-in-time telemetry sample for a single node.
type SystemMetrics struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TimestampUnixNano  int64                  `protobuf:"varint,1,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	NodeId             string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Cpu                *CpuMetrics            `protobuf:"bytes,3,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory             *MemoryMetrics         `protobuf:"bytes,4,opt,name=memory,proto3" json:"memory,omitempty"`
	Power              *PowerMetrics          `protobuf:"bytes,5,opt,name=power,proto3" json:"power,omitempty"`
	Network            *NetworkMetrics        `protobuf:"bytes,6,opt,name=network,proto3" json:"network,omitempty"`
	Processes          []*ProcessMetric       `protobuf:"bytes,7,rep,name=processes,proto3" json:"processes,omitempty"`
	CpuModel           string                 `protobuf:"bytes,8,opt,name=cpu_model,json=cpuModel,proto3" json:"cpu_model,omitempty"`
	Os                 string                 `protobuf:"bytes,9,opt,name=os,proto3" json:"os,omitempty"`
	Arch               string                 `protobuf:"bytes,10,opt,name=arch,proto3" json:"arch,omitempty"`
	ProcessesAvailable bool                   `protobuf:"varint,11,opt,name=processes_available,json=processesAvailable,proto3" json:"processes_available,omitempty"`
	Twamp              *TwampMetrics          `protobuf:"bytes,12,opt,name=twamp,proto3" json:"twamp,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SystemMetrics) Reset() {
	*x = SystemMetrics{}
	mi := &file_madtom_v1_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMetrics) ProtoMessage() {}

func (x *SystemMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_madtom_v1_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMetrics.ProtoReflect.Descriptor instead.
func (*SystemMetrics) Descriptor() ([]byte, []int) {
	return file_madtom_v1_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *SystemMetrics) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

func (x *SystemMetrics) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SystemMetrics) GetCpu() *CpuMetrics {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *SystemMetrics) GetMemory() *MemoryMetrics {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *SystemMetrics) GetPower() *PowerMetrics {
	if x != nil {
		return x.Power
	}
	return nil
}

func (x *SystemMetrics) GetNetwork() *NetworkMetrics {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *SystemMetrics) GetProcesses() []*ProcessMetric {
	if x != nil {
		return x.Processes
	}
	return nil
}

func (x *SystemMetrics) GetCpuModel() string {
	if x != nil {
		return x.CpuModel
	}
	return ""
}

func (x *SystemMetrics) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *SystemMetrics) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *SystemMetrics) GetProcessesAvailable() bool {
	if x != nil {
		return x.ProcessesAvailable
	}
	return false
}

func (x *SystemMetrics) GetTwamp() *TwampMetrics {
	if x != nil {
		return x.Twamp
	}
	return nil
}

// CpuMetrics details processor performance and core states.
type CpuMetrics struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalPct        float64                `protobuf:"fixed64,1,opt,name=total_pct,json=totalPct,proto3" json:"total_pct,omitempty"`
	PerCorePct      []float64              `protobuf:"fixed64,2,rep,packed,name=per_core_pct,json=perCorePct,proto3" json:"per_core_pct,omitempty"` // For DetailedCoreMatrixControl
	UserPct         float64                `protobuf:"fixed64,3,opt,name=user_pct,json=userPct,proto3" json:"user_pct,omitempty"`
	SystemPct       float64                `protobuf:"fixed64,4,opt,name=system_pct,json=systemPct,proto3" json:"system_pct,omitempty"`
	IowaitPct       float64                `protobuf:"fixed64,5,opt,name=iowait_pct,json=iowaitPct,proto3" json:"iowait_pct,omitempty"`
	IdlePct         float64                `protobuf:"fixed64,6,opt,name=idle_pct,json=idlePct,proto3" json:"idle_pct,omitempty"`
	Load_1M         float64                `protobuf:"fixed64,7,opt,name=load_1m,json=load1m,proto3" json:"load_1m,omitempty"`
	Load_5M         float64                `protobuf:"fixed64,8,opt,name=load_5m,json=load5m,proto3" json:"load_5m,omitempty"`
	Load_15M        float64                `protobuf:"fixed64,9,opt,name=load_15m,json=load15m,proto3" json:"load_15m,omitempty"`
	CtxtSwitchesSec uint64                 `protobuf:"varint,10,opt,name=ctxt_switches_sec,json=ctxtSwitchesSec,proto3" json:"ctxt_switches_sec,omitempty"`
	CoreFreqMhz     []uint32               `protobuf:"varint,11,rep,packed,name=core_freq_mhz,json=coreFreqMhz,proto3" json:"core_freq_mhz,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CpuMetrics) Reset() {
	*x = CpuMetrics{}
	mi := &file_madtom_v1_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuMetrics) ProtoMessage() {}

func (x *CpuMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_madtom_v1_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuMetrics.ProtoReflect.Descriptor instead.
func (*CpuMetrics) Descriptor() ([]byte, []int) {
	return file_madtom_v1_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *CpuMetrics) GetTotalPct() float64 {
	if x != nil {
		return x.TotalPct
	}
	return 0
}

func (x *CpuMetrics) GetPerCorePct() []float64 {
	if x != nil {
		return x.PerCorePct
	}
	return nil
}

func (x *CpuMetrics) GetUserPct() float64 {
	if x != nil {
		return x.UserPct
	}
	return 0
}

func (x *CpuMetrics) GetSystemPct() float64 {
	if x != nil {
		return x.SystemPct
	}
	return 0
}

func (x *CpuMetrics) GetIowaitPct() float64 {
	if x != nil {
		return x.IowaitPct
	}
	return 0
}

func (x *CpuMetrics) GetIdlePct() float64 {
	if x != nil {
		return x.IdlePct
	}
	return 0
}

func (x *CpuMetrics) GetLoad_1M() float64 {
	if x != nil {
		return x.Load_1M
	}
	return 0
}

func (x *CpuMetrics) GetLoad_5M() float64 {
	if x != nil {
		return x.Load_5M
	}
	return 0
}

func (x *CpuMetrics) GetLoad_15M() float64 {
	if x != nil {
		return x.Load_15M
	}
	return 0
}

func (x *CpuMetrics) GetCtxtSwitchesSec() uint64 {
	if x != nil {
		return x.CtxtSwitchesSec
	}
	return 0
}

func (x *CpuMetrics) GetCoreFreqMhz() []uint32 {
	if x != nil {
		return x.CoreFreqMhz
	}
	return nil
}

// MemoryMetrics captures all system memory, swap, and compressed ZRAM metrics.
type MemoryMetrics struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MemTotalBytes     uint64                 `protobuf:"varint,1,opt,name=mem_total_bytes,json=memTotalBytes,proto3" json:"mem_total_bytes,omitempty"`
	MemFreeBytes      uint64                 `protobuf:"varint,2,opt,name=mem_free_bytes,json=memFreeBytes,proto3" json:"mem_free_bytes,omitempty"`
	MemAvailableBytes uint64                 `protobuf:"varint,3,opt,name=mem_available_bytes,json=memAvailableBytes,proto3" json:"mem_available_bytes,omitempty"`
	BuffersBytes      uint64                 `protobuf:"varint,4,opt,name=buffers_bytes,json=buffersBytes,proto3" json:"buffers_bytes,omitempty"`
	CachedBytes       uint64                 `protobuf:"varint,5,opt,name=cached_bytes,json=cachedBytes,proto3" json:"cached_bytes,omitempty"`
	DirtyBytes        uint64                 `protobuf:"varint,6,opt,name=dirty_bytes,json=dirtyBytes,proto3" json:"dirty_bytes,omitempty"`
	WritebackBytes    uint64                 `protobuf:"varint,7,opt,name=writeback_bytes,json=writebackBytes,proto3" json:"writeback_bytes,omitempty"`
	SwapTotalBytes    uint64                 `protobuf:"varint,8,opt,name=swap_total_bytes,json=swapTotalBytes,proto3" json:"swap_total_bytes,omitempty"`
	SwapFreeBytes     uint64                 `protobuf:"varint,9,opt,name=swap_free_bytes,json=swapFreeBytes,proto3" json:"swap_free_bytes,omitempty"`
	ZramOrigBytes     uint64                 `protobuf:"varint,10,opt,name=zram_orig_bytes,json=zramOrigBytes,proto3" json:"zram_orig_bytes,omitempty"`
	ZramComprBytes    uint64                 `protobuf:"varint,11,opt,name=zram_compr_bytes,json=zramComprBytes,proto3" json:"zram_compr_bytes,omitempty"`
	ZramRatio         float64                `protobuf:"fixed64,12,opt,name=zram_ratio,json=zramRatio,proto3" json:"zram_ratio,omitempty"`
	PgfaultSec        uint64                 `protobuf:"varint,13,opt,name=pgfault_sec,json=pgfaultSec,proto3" json:"pgfault_sec,omitempty"`
	PgmajfaultSec     uint64                 `protobuf:"varint,14,opt,name=pgmajfault_sec,json=pgmajfaultSec,proto3" json:"pgmajfault_sec,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MemoryMetrics) Reset() {
	*x = MemoryMetrics{}
	mi := &file_madtom_v1_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryMetrics) ProtoMessage() {}

func (x *MemoryMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_madtom_v1_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryMetrics.ProtoReflect.Descriptor instead.
func (*MemoryMetrics) Descriptor() ([]byte, []int) {
	return file_madtom_v1_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *MemoryMetrics) GetMemTotalBytes() uint64 {
	if x != nil {
		return x.MemTotalBytes
	}
	return 0
}

func (x *MemoryMetrics) GetMemFreeBytes() uint64 {
	if x != nil {
		return x.MemFreeBytes
	}
	return 0
}

func (x *MemoryMetrics) GetMemAvailableBytes() uint64 {
	if x != nil {
		return x.MemAvailableBytes
	}
	return 0
}

func (x *MemoryMetrics) GetBuffersBytes() uint64 {
	if x != nil {
		return x.BuffersBytes
	}
	return 0
}

func (x *MemoryMetrics) GetCachedBytes() uint64 {
	if x != nil {
		return x.CachedBytes
	}
	return 0
}

func (x *MemoryMetrics) GetDirtyBytes() uint64 {
	if x != nil {
		return x.DirtyBytes
	}
	return 0
}

func (x *MemoryMetrics) GetWritebackBytes() uint64 {
	if x != nil {
		return x.WritebackBytes
	}
	return 0
}

func (x *MemoryMetrics) GetSwapTotalBytes() uint64 {
	if x != nil {
		return x.SwapTotalBytes
	}
	return 0
}

func (x *MemoryMetrics) GetSwapFreeBytes() uint64 {
	if x != nil {
		return x.SwapFreeBytes
	}
	return 0
}

func (x *MemoryMetrics) GetZramOrigBytes() uint64 {
	if x != nil {
		return x.ZramOrigBytes
	}
	return 0
}

func (x *MemoryMetrics) GetZramComprBytes() uint64 {
	if x != nil {
		return x.ZramComprBytes
	}
	return 0
}

func (x *MemoryMetrics) GetZramRatio() float64 {
	if x != nil {
		return x.ZramRatio
	}
	return 0
}

func (x *MemoryMetrics) GetPgfaultSec() uint64 {
	if x != nil {
		return x.PgfaultSec
	}
	return 0
}

func (x *MemoryMetrics) GetPgmajfaultSec() uint64 {
	if x != nil {
		return x.PgmajfaultSec
	}
	return 0
}

// PowerMetrics details AC line power, battery state, health and draw.
type PowerMetrics struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AcPlugged        bool                   `protobuf:"varint,1,opt,name=ac_plugged,json=acPlugged,proto3" json:"ac_plugged,omitempty"`
	BatteryPresent   bool                   `protobuf:"varint,2,opt,name=battery_present,json=batteryPresent,proto3" json:"battery_present,omitempty"`
	BatteryState     string                 `protobuf:"bytes,3,opt,name=battery_state,json=batteryState,proto3" json:"battery_state,omitempty"` // "Charging", "Discharging", "Full", "Unknown"
	BatteryPct       float64                `protobuf:"fixed64,4,opt,name=battery_pct,json=batteryPct,proto3" json:"battery_pct,omitempty"`
	CurrentEnergyWh  float64                `protobuf:"fixed64,5,opt,name=current_energy_wh,json=currentEnergyWh,proto3" json:"current_energy_wh,omitempty"`
	DesignCapacityWh float64                `protobuf:"fixed64,6,opt,name=design_capacity_wh,json=designCapacityWh,proto3" json:"design_capacity_wh,omitempty"`
	RateWatts        float64                `protobuf:"fixed64,7,opt,name=rate_watts,json=rateWatts,proto3" json:"rate_watts,omitempty"`
	Cycles           uint32                 `protobuf:"varint,8,opt,name=cycles,proto3" json:"cycles,omitempty"`
	HealthPct        float64                `protobuf:"fixed64,9,opt,name=health_pct,json=healthPct,proto3" json:"health_pct,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PowerMetrics) Reset() {
	*x = PowerMetrics{}
	mi := &file_madtom_v1_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowerMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerMetrics) ProtoMessage() {}

func (x *PowerMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_madtom_v1_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerMetrics.ProtoReflect.Descriptor instead.
func (*PowerMetrics) Descriptor() ([]byte, []int) {
	return file_madtom_v1_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *PowerMetrics) GetAcPlugged() bool {
	if x != nil {
		return x.AcPlugged
	}
	return false
}

func (x *PowerMetrics) GetBatteryPresent() bool {
	if x != nil {
		return x.BatteryPresent
	}
	return false
}

func (x *PowerMetrics) GetBatteryState() string {
	if x != nil {
		return x.BatteryState
	}
	return ""
}

func (x *PowerMetrics) GetBatteryPct() float64 {
	if x != nil {
		return x.BatteryPct
	}
	return 0
}

func (x *PowerMetrics) GetCurrentEnergyWh() float64 {
	if x != nil {
		return x.CurrentEnergyWh
	}
	return 0
}

func (x *PowerMetrics) GetDesignCapacityWh() float64 {
	if x != nil {
		return x.DesignCapacityWh
	}
	return 0
}

func (x *PowerMetrics) GetRateWatts() float64 {
	if x != nil {
		return x.RateWatts
	}
	return 0
}

func (x *PowerMetrics) GetCycles() uint32 {
	if x != nil {
		return x.Cycles
	}
	return 0
}

func (x *PowerMetrics) GetHealthPct() float64 {
	if x != nil {
		return x.HealthPct
	}
	return 0
}

// NetworkMetrics contains individual network interfaces.
type NetworkMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interfaces    []*NicMetric           `protobuf:"bytes,1,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkMetrics) Reset() {
	*x = NetworkMetrics{}
	mi := &file_madtom_v1_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkMetrics) ProtoMessage() {}

func (x *NetworkMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_madtom_v1_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkMetrics.ProtoReflect.Descriptor instead.
func (*NetworkMetrics) Descriptor() ([]byte, []int) {
	return file_madtom_v1_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *NetworkMetrics) GetInterfaces() []*NicMetric {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

// NicMetric details traffic counters and physical link parameters for a single NIC.
type NicMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RxBytes       uint64                 `protobuf:"varint,2,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	TxBytes       uint64                 `protobuf:"varint,3,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	RxPackets     uint64                 `protobuf:"varint,4,opt,name=rx_packets,json=rxPackets,proto3" json:"rx_packets,omitempty"`
	TxPackets     uint64                 `protobuf:"varint,5,opt,name=tx_packets,json=txPackets,proto3" json:"tx_packets,omitempty"`
	RxDropped     uint64                 `protobuf:"varint,6,opt,name=rx_dropped,json=rxDropped,proto3" json:"rx_dropped,omitempty"`
	TxDropped     uint64                 `protobuf:"varint,7,opt,name=tx_dropped,json=txDropped,proto3" json:"tx_dropped,omitempty"`
	RxErrors      uint64                 `protobuf:"varint,8,opt,name=rx_errors,json=rxErrors,proto3" json:"rx_errors,omitempty"`
	TxErrors      uint64                 `protobuf:"varint,9,opt,name=tx_errors,json=txErrors,proto3" json:"tx_errors,omitempty"`
	LinkSpeedMbps uint32                 `protobuf:"varint,10,opt,name=link_speed_mbps,json=linkSpeedMbps,proto3" json:"link_speed_mbps,omitempty"`
	CarrierUp     bool                   `protobuf:"varint,11,opt,name=carrier_up,json=carrierUp,proto3" json:"carrier_up,omitempty"`
	Mtu           uint32                 `protobuf:"varint,12,opt,name=mtu,proto3" json:"mtu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NicMetric) Reset() {
	*x = NicMetric{}
	mi := &file_madtom_v1_metrics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NicMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NicMetric) ProtoMessage() {}

func (x *NicMetric) ProtoReflect() protoreflect.Message {
	mi := &file_madtom_v1_metrics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NicMetric.ProtoReflect.Descriptor instead.
func (*NicMetric) Descriptor() ([]byte, []int) {
	return file_madtom_v1_metrics_proto_rawDescGZIP(), []int{5}
}

func (x *NicMetric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NicMetric) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *NicMetric) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *NicMetric) GetRxPackets() uint64 {
	if x != nil {
		return x.RxPackets
	}
	return 0
}

func (x *NicMetric) GetTxPackets() uint64 {
	if x != nil {
		return x.TxPackets
	}
	return 0
}

func (x *NicMetric) GetRxDropped() uint64 {
	if x != nil {
		return x.RxDropped
	}
	return 0
}

func (x *NicMetric) GetTxDropped() uint64 {
	if x != nil {
		return x.TxDropped
	}
	return 0
}

func (x *NicMetric) GetRxErrors() uint64 {
	if x != nil {
		return x.RxErrors
	}
	return 0
}

func (x *NicMetric) GetTxErrors() uint64 {
	if x != nil {
		return x.TxErrors
	}
	return 0
}

func (x *NicMetric) GetLinkSpeedMbps() uint32 {
	if x != nil {
		return x.LinkSpeedMbps
	}
	return 0
}

func (x *NicMetric) GetCarrierUp() bool {
	if x != nil {
		return x.CarrierUp
	}
	return false
}

func (x *NicMetric) GetMtu() uint32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

type ProcessMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Threads       uint32                 `protobuf:"varint,4,opt,name=threads,proto3" json:"threads,omitempty"`
	CpuPct        float64                `protobuf:"fixed64,5,opt,name=cpu_pct,json=cpuPct,proto3" json:"cpu_pct,omitempty"`
	RssBytes      uint64                 `protobuf:"varint,6,opt,name=rss_bytes,json=rssBytes,proto3" json:"rss_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessMetric) Reset() {
	*x = ProcessMetric{}
	mi := &file_madtom_v1_metrics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessMetric) ProtoMessage() {}

func (x *ProcessMetric) ProtoReflect() protoreflect.Message {
	mi := &file_madtom_v1_metrics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessMetric.ProtoReflect.Descriptor instead.
func (*ProcessMetric) Descriptor() ([]byte, []int) {
	return file_madtom_v1_metrics_proto_rawDescGZIP(), []int{6}
}

func (x *ProcessMetric) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessMetric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessMetric) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ProcessMetric) GetThreads() uint32 {
	if x != nil {
		return x.Threads
	}
	return 0
}

func (x *ProcessMetric) GetCpuPct() float64 {
	if x != nil {
		return x.CpuPct
	}
	return 0
}

func (x *ProcessMetric) GetRssBytes() uint64 {
	if x != nil {
		return x.RssBytes
	}
	return 0
}

type TwampMetrics struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Target          string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Available       bool                   `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	Error           string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	RttMs           float64                `protobuf:"fixed64,4,opt,name=rtt_ms,json=rttMs,proto3" json:"rtt_ms,omitempty"`
	ForwardMs       float64                `protobuf:"fixed64,5,opt,name=forward_ms,json=forwardMs,proto3" json:"forward_ms,omitempty"`
	ReverseMs       float64                `protobuf:"fixed64,6,opt,name=reverse_ms,json=reverseMs,proto3" json:"reverse_ms,omitempty"`
	OneWayAvailable bool                   `protobuf:"varint,7,opt,name=one_way_available,json=oneWayAvailable,proto3" json:"one_way_available,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TwampMetrics) Reset() {
	*x = TwampMetrics{}
	mi := &file_madtom_v1_metrics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwampMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwampMetrics) ProtoMessage() {}

func (x *TwampMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_madtom_v1_metrics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwampMetrics.ProtoReflect.Descriptor instead.
func (*TwampMetrics) Descriptor() ([]byte, []int) {
	return file_madtom_v1_metrics_proto_rawDescGZIP(), []int{7}
}

func (x *TwampMetrics) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *TwampMetrics) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *TwampMetrics) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TwampMetrics) GetRttMs() float64 {
	if x != nil {
		return x.RttMs
	}
	return 0
}

func (x *TwampMetrics) GetForwardMs() float64 {
	if x != nil {
		return x.ForwardMs
	}
	return 0
}

func (x *TwampMetrics) GetReverseMs() float64 {
	if x != nil {
		return x.ReverseMs
	}
	return 0
}

func (x *TwampMetrics) GetOneWayAvailable() bool {
	if x != nil {
		return x.OneWayAvailable
	}
	return false
}

var File_madtom_v1_metrics_proto protoreflect.FileDescriptor

const file_madtom_v1_metrics_proto_rawDesc = "" +
	"\n" +
	"\x17madtom/v1/metrics.proto\x12\tmadtom.v1\"\xf0\x03\n" +
	"\rSystemMetrics\x12.\n" +
	"\x13timestamp_unix_nano\x18\x01 \x01(\x03R\x11timestampUnixNano\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12'\n" +
	"\x03cpu\x18\x03 \x01(\v2\x15.madtom.v1.CpuMetricsR\x03cpu\x120\n" +
	"\x06memory\x18\x04 \x01(\v2\x18.madtom.v1.MemoryMetricsR\x06memory\x12-\n" +
	"\x05power\x18\x05 \x01(\v2\x17.madtom.v1.PowerMetricsR\x05power\x123\n" +
	"\anetwork\x18\x06 \x01(\v2\x19.madtom.v1.NetworkMetricsR\anetwork\x126\n" +
	"\tprocesses\x18\a \x03(\v2\x18.madtom.v1.ProcessMetricR\tprocesses\x12\x1b\n" +
	"\tcpu_model\x18\b \x01(\tR\bcpuModel\x12\x0e\n" +
	"\x02os\x18\t \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\n" +
	" \x01(\tR\x04arch\x12/\n" +
	"\x13processes_available\x18\v \x01(\bR\x12processesAvailable\x12-\n" +
	"\x05twamp\x18\f \x01(\v2\x17.madtom.v1.TwampMetricsR\x05twamp\"\xdc\x02\n" +
	"\n" +
	"CpuMetrics\x12\x1b\n" +
	"\ttotal_pct\x18\x01 \x01(\x01R\btotalPct\x12 \n" +
	"\fper_core_pct\x18\x02 \x03(\x01R\n" +
	"perCorePct\x12\x19\n" +
	"\buser_pct\x18\x03 \x01(\x01R\auserPct\x12\x1d\n" +
	"\n" +
	"system_pct\x18\x04 \x01(\x01R\tsystemPct\x12\x1d\n" +
	"\n" +
	"iowait_pct\x18\x05 \x01(\x01R\tiowaitPct\x12\x19\n" +
	"\bidle_pct\x18\x06 \x01(\x01R\aidlePct\x12\x17\n" +
	"\aload_1m\x18\a \x01(\x01R\x06load1m\x12\x17\n" +
	"\aload_5m\x18\b \x01(\x01R\x06load5m\x12\x19\n" +
	"\bload_15m\x18\t \x01(\x01R\aload15m\x12*\n" +
	"\x11ctxt_switches_sec\x18\n" +
	" \x01(\x04R\x0fctxtSwitchesSec\x12\"\n" +
	"\rcore_freq_mhz\x18\v \x03(\rR\vcoreFreqMhz\"\xaa\x04\n" +
	"\rMemoryMetrics\x12&\n" +
	"\x0fmem_total_bytes\x18\x01 \x01(\x04R\rmemTotalBytes\x12$\n" +
	"\x0emem_free_bytes\x18\x02 \x01(\x04R\fmemFreeBytes\x12.\n" +
	"\x13mem_available_bytes\x18\x03 \x01(\x04R\x11memAvailableBytes\x12#\n" +
	"\rbuffers_bytes\x18\x04 \x01(\x04R\fbuffersBytes\x12!\n" +
	"\fcached_bytes\x18\x05 \x01(\x04R\vcachedBytes\x12\x1f\n" +
	"\vdirty_bytes\x18\x06 \x01(\x04R\n" +
	"dirtyBytes\x12'\n" +
	"\x0fwriteback_bytes\x18\a \x01(\x04R\x0ewritebackBytes\x12(\n" +
	"\x10swap_total_bytes\x18\b \x01(\x04R\x0eswapTotalBytes\x12&\n" +
	"\x0fswap_free_bytes\x18\t \x01(\x04R\rswapFreeBytes\x12&\n" +
	"\x0fzram_orig_bytes\x18\n" +
	" \x01(\x04R\rzramOrigBytes\x12(\n" +
	"\x10zram_compr_bytes\x18\v \x01(\x04R\x0ezramComprBytes\x12\x1d\n" +
	"\n" +
	"zram_ratio\x18\f \x01(\x01R\tzramRatio\x12\x1f\n" +
	"\vpgfault_sec\x18\r \x01(\x04R\n" +
	"pgfaultSec\x12%\n" +
	"\x0epgmajfault_sec\x18\x0e \x01(\x04R\rpgmajfaultSec\"\xcc\x02\n" +
	"\fPowerMetrics\x12\x1d\n" +
	"\n" +
	"ac_plugged\x18\x01 \x01(\bR\tacPlugged\x12'\n" +
	"\x0fbattery_present\x18\x02 \x01(\bR\x0ebatteryPresent\x12#\n" +
	"\rbattery_state\x18\x03 \x01(\tR\fbatteryState\x12\x1f\n" +
	"\vbattery_pct\x18\x04 \x01(\x01R\n" +
	"batteryPct\x12*\n" +
	"\x11current_energy_wh\x18\x05 \x01(\x01R\x0fcurrentEnergyWh\x12,\n" +
	"\x12design_capacity_wh\x18\x06 \x01(\x01R\x10designCapacityWh\x12\x1d\n" +
	"\n" +
	"rate_watts\x18\a \x01(\x01R\trateWatts\x12\x16\n" +
	"\x06cycles\x18\b \x01(\rR\x06cycles\x12\x1d\n" +
	"\n" +
	"health_pct\x18\t \x01(\x01R\thealthPct\"F\n" +
	"\x0eNetworkMetrics\x124\n" +
	"\n" +
	"interfaces\x18\x01 \x03(\v2\x14.madtom.v1.NicMetricR\n" +
	"interfaces\"\xe4\x02\n" +
	"\tNicMetric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\brx_bytes\x18\x02 \x01(\x04R\arxBytes\x12\x19\n" +
	"\btx_bytes\x18\x03 \x01(\x04R\atxBytes\x12\x1d\n" +
	"\n" +
	"rx_packets\x18\x04 \x01(\x04R\trxPackets\x12\x1d\n" +
	"\n" +
	"tx_packets\x18\x05 \x01(\x04R\ttxPackets\x12\x1d\n" +
	"\n" +
	"rx_dropped\x18\x06 \x01(\x04R\trxDropped\x12\x1d\n" +
	"\n" +
	"tx_dropped\x18\a \x01(\x04R\ttxDropped\x12\x1b\n" +
	"\trx_errors\x18\b \x01(\x04R\brxErrors\x12\x1b\n" +
	"\ttx_errors\x18\t \x01(\x04R\btxErrors\x12&\n" +
	"\x0flink_speed_mbps\x18\n" +
	" \x01(\rR\rlinkSpeedMbps\x12\x1d\n" +
	"\n" +
	"carrier_up\x18\v \x01(\bR\tcarrierUp\x12\x10\n" +
	"\x03mtu\x18\f \x01(\rR\x03mtu\"\x99\x01\n" +
	"\rProcessMetric\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x18\n" +
	"\athreads\x18\x04 \x01(\rR\athreads\x12\x17\n" +
	"\acpu_pct\x18\x05 \x01(\x01R\x06cpuPct\x12\x1b\n" +
	"\trss_bytes\x18\x06 \x01(\x04R\brssBytes\"\xdb\x01\n" +
	"\fTwampMetrics\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\bR\tavailable\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x15\n" +
	"\x06rtt_ms\x18\x04 \x01(\x01R\x05rttMs\x12\x1d\n" +
	"\n" +
	"forward_ms\x18\x05 \x01(\x01R\tforwardMs\x12\x1d\n" +
	"\n" +
	"reverse_ms\x18\x06 \x01(\x01R\treverseMs\x12*\n" +
	"\x11one_way_available\x18\a \x01(\bR\x0foneWayAvailableBYZ3github.com/DarkDuck007/madtom/pkg/proto/v1;madtomv1\xaa\x02!MADTOM.Plugins.Telemetry.Proto.V1b\x06proto3"

var (
	file_madtom_v1_metrics_proto_rawDescOnce sync.Once
	file_madtom_v1_metrics_proto_rawDescData []byte
)

func file_madtom_v1_metrics_proto_rawDescGZIP() []byte {
	file_madtom_v1_metrics_proto_rawDescOnce.Do(func() {
		file_madtom_v1_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_madtom_v1_metrics_proto_rawDesc), len(file_madtom_v1_metrics_proto_rawDesc)))
	})
	return file_madtom_v1_metrics_proto_rawDescData
}

var file_madtom_v1_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_madtom_v1_metrics_proto_goTypes = []any{
	(*SystemMetrics)(nil),  // 0: madtom.v1.SystemMetrics
	(*CpuMetrics)(nil),     // 1: madtom.v1.CpuMetrics
	(*MemoryMetrics)(nil),  // 2: madtom.v1.MemoryMetrics
	(*PowerMetrics)(nil),   // 3: madtom.v1.PowerMetrics
	(*NetworkMetrics)(nil), // 4: madtom.v1.NetworkMetrics
	(*NicMetric)(nil),      // 5: madtom.v1.NicMetric
	(*ProcessMetric)(nil),  // 6: madtom.v1.ProcessMetric
	(*TwampMetrics)(nil),   // 7: madtom.v1.TwampMetrics
}
var file_madtom_v1_metrics_proto_depIdxs = []int32{
	1, // 0: madtom.v1.SystemMetrics.cpu:type_name -> madtom.v1.CpuMetrics
	2, // 1: madtom.v1.SystemMetrics.memory:type_name -> madtom.v1.MemoryMetrics
	3, // 2: madtom.v1.SystemMetrics.power:type_name -> madtom.v1.PowerMetrics
	4, // 3: madtom.v1.SystemMetrics.network:type_name -> madtom.v1.NetworkMetrics
	6, // 4: madtom.v1.SystemMetrics.processes:type_name -> madtom.v1.ProcessMetric
	7, // 5: madtom.v1.SystemMetrics.twamp:type_name -> madtom.v1.TwampMetrics
	5, // 6: madtom.v1.NetworkMetrics.interfaces:type_name -> madtom.v1.NicMetric
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_madtom_v1_metrics_proto_init() }
func file_madtom_v1_metrics_proto_init() {
	if File_madtom_v1_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_madtom_v1_metrics_proto_rawDesc), len(file_madtom_v1_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_madtom_v1_metrics_proto_goTypes,
		DependencyIndexes: file_madtom_v1_metrics_proto_depIdxs,
		MessageInfos:      file_madtom_v1_metrics_proto_msgTypes,
	}.Build()
	File_madtom_v1_metrics_proto = out.File
	file_madtom_v1_metrics_proto_goTypes = nil
	file_madtom_v1_metrics_proto_depIdxs = nil
}
