// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: madtom/v1/query.proto

package madtomv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QueryService_ListNodes_FullMethodName      = "/madtom.v1.QueryService/ListNodes"
	QueryService_QueryRange_FullMethodName     = "/madtom.v1.QueryService/QueryRange"
	QueryService_SubscribeLive_FullMethodName  = "/madtom.v1.QueryService/SubscribeLive"
	QueryService_GetLogStats_FullMethodName    = "/madtom.v1.QueryService/GetLogStats"
	QueryService_QueryLogChunks_FullMethodName = "/madtom.v1.QueryService/QueryLogChunks"
	QueryService_SubscribeLogs_FullMethodName  = "/madtom.v1.QueryService/SubscribeLogs"
)

// QueryServiceClient is the client API for QueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// QueryService exposes time-series querying and real-time streaming to the UI.
type QueryServiceClient interface {
	// Discovers all nodes registered with this collector.
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
	// Resolution-adaptive historical metric query using LTTB downsampling.
	QueryRange(ctx context.Context, in *RangeQueryRequest, opts ...grpc.CallOption) (*RangeQueryResponse, error)
	// Real-time 1Hz streaming feed for actively viewed cards/nodes.
	SubscribeLive(ctx context.Context, in *LiveSubscriptionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LiveTelemetryEvent], error)
	// System logs query and streaming endpoints.
	GetLogStats(ctx context.Context, in *LogStatsRequest, opts ...grpc.CallOption) (*LogStatsResponse, error)
	QueryLogChunks(ctx context.Context, in *LogChunkQuery, opts ...grpc.CallOption) (*LogChunkResponse, error)
	SubscribeLogs(ctx context.Context, in *LogSubscription, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunk], error)
}

type queryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryServiceClient(cc grpc.ClientConnInterface) QueryServiceClient {
	return &queryServiceClient{cc}
}

func (c *queryServiceClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, QueryService_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) QueryRange(ctx context.Context, in *RangeQueryRequest, opts ...grpc.CallOption) (*RangeQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RangeQueryResponse)
	err := c.cc.Invoke(ctx, QueryService_QueryRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) SubscribeLive(ctx context.Context, in *LiveSubscriptionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LiveTelemetryEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &QueryService_ServiceDesc.Streams[0], QueryService_SubscribeLive_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LiveSubscriptionRequest, LiveTelemetryEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QueryService_SubscribeLiveClient = grpc.ServerStreamingClient[LiveTelemetryEvent]

func (c *queryServiceClient) GetLogStats(ctx context.Context, in *LogStatsRequest, opts ...grpc.CallOption) (*LogStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogStatsResponse)
	err := c.cc.Invoke(ctx, QueryService_GetLogStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) QueryLogChunks(ctx context.Context, in *LogChunkQuery, opts ...grpc.CallOption) (*LogChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogChunkResponse)
	err := c.cc.Invoke(ctx, QueryService_QueryLogChunks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) SubscribeLogs(ctx context.Context, in *LogSubscription, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &QueryService_ServiceDesc.Streams[1], QueryService_SubscribeLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogSubscription, LogChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QueryService_SubscribeLogsClient = grpc.ServerStreamingClient[LogChunk]

// QueryServiceServer is the server API for QueryService service.
// All implementations must embed UnimplementedQueryServiceServer
// for forward compatibility.
//
// QueryService exposes time-series querying and real-time streaming to the UI.
type QueryServiceServer interface {
	// Discovers all nodes registered with this collector.
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	// Resolution-adaptive historical metric query using LTTB downsampling.
	QueryRange(context.Context, *RangeQueryRequest) (*RangeQueryResponse, error)
	// Real-time 1Hz streaming feed for actively viewed cards/nodes.
	SubscribeLive(*LiveSubscriptionRequest, grpc.ServerStreamingServer[LiveTelemetryEvent]) error
	// System logs query and streaming endpoints.
	GetLogStats(context.Context, *LogStatsRequest) (*LogStatsResponse, error)
	QueryLogChunks(context.Context, *LogChunkQuery) (*LogChunkResponse, error)
	SubscribeLogs(*LogSubscription, grpc.ServerStreamingServer[LogChunk]) error
	mustEmbedUnimplementedQueryServiceServer()
}

// UnimplementedQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServiceServer struct{}

func (UnimplementedQueryServiceServer) ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedQueryServiceServer) QueryRange(context.Context, *RangeQueryRequest) (*RangeQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryRange not implemented")
}
func (UnimplementedQueryServiceServer) SubscribeLive(*LiveSubscriptionRequest, grpc.ServerStreamingServer[LiveTelemetryEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeLive not implemented")
}
func (UnimplementedQueryServiceServer) GetLogStats(context.Context, *LogStatsRequest) (*LogStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLogStats not implemented")
}
func (UnimplementedQueryServiceServer) QueryLogChunks(context.Context, *LogChunkQuery) (*LogChunkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryLogChunks not implemented")
}
func (UnimplementedQueryServiceServer) SubscribeLogs(*LogSubscription, grpc.ServerStreamingServer[LogChunk]) error {
	return status.Error(codes.Unimplemented, "method SubscribeLogs not implemented")
}
func (UnimplementedQueryServiceServer) mustEmbedUnimplementedQueryServiceServer() {}
func (UnimplementedQueryServiceServer) testEmbeddedByValue()                      {}

// UnsafeQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServiceServer will
// result in compilation errors.
type UnsafeQueryServiceServer interface {
	mustEmbedUnimplementedQueryServiceServer()
}

func RegisterQueryServiceServer(s grpc.ServiceRegistrar, srv QueryServiceServer) {
	// If the following call panics, it indicates UnimplementedQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QueryService_ServiceDesc, srv)
}

func _QueryService_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_QueryRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RangeQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).QueryRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_QueryRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).QueryRange(ctx, req.(*RangeQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_SubscribeLive_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LiveSubscriptionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QueryServiceServer).SubscribeLive(m, &grpc.GenericServerStream[LiveSubscriptionRequest, LiveTelemetryEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QueryService_SubscribeLiveServer = grpc.ServerStreamingServer[LiveTelemetryEvent]

func _QueryService_GetLogStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).GetLogStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_GetLogStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).GetLogStats(ctx, req.(*LogStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_QueryLogChunks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogChunkQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).QueryLogChunks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_QueryLogChunks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).QueryLogChunks(ctx, req.(*LogChunkQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_SubscribeLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogSubscription)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QueryServiceServer).SubscribeLogs(m, &grpc.GenericServerStream[LogSubscription, LogChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QueryService_SubscribeLogsServer = grpc.ServerStreamingServer[LogChunk]

// QueryService_ServiceDesc is the grpc.ServiceDesc for QueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "madtom.v1.QueryService",
	HandlerType: (*QueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListNodes",
			Handler:    _QueryService_ListNodes_Handler,
		},
		{
			MethodName: "QueryRange",
			Handler:    _QueryService_QueryRange_Handler,
		},
		{
			MethodName: "GetLogStats",
			Handler:    _QueryService_GetLogStats_Handler,
		},
		{
			MethodName: "QueryLogChunks",
			Handler:    _QueryService_QueryLogChunks_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeLive",
			Handler:       _QueryService_SubscribeLive_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeLogs",
			Handler:       _QueryService_SubscribeLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "madtom/v1/query.proto",
}
