// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: madtom/v1/query.proto

package madtomv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_madtom_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_madtom_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_madtom_v1_query_proto_rawDescGZIP(), []int{0}
}

type NodeInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeId           string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Hostname         string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os               string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Arch             string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	Status           string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // "ONLINE", "STALE", "OFFLINE"
	LastSeenUnixNano int64                  `protobuf:"varint,6,opt,name=last_seen_unix_nano,json=lastSeenUnixNano,proto3" json:"last_seen_unix_nano,omitempty"`
	ConnectionMode   string                 `protobuf:"bytes,7,opt,name=connection_mode,json=connectionMode,proto3" json:"connection_mode,omitempty"` // "PUSH", "PULL"
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_madtom_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_madtom_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_madtom_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *NodeInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *NodeInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *NodeInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NodeInfo) GetLastSeenUnixNano() int64 {
	if x != nil {
		return x.LastSeenUnixNano
	}
	return 0
}

func (x *NodeInfo) GetConnectionMode() string {
	if x != nil {
		return x.ConnectionMode
	}
	return ""
}

type ListNodesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Negotiated response envelope; decoded content is this same message type.
	ZstdPayload             []byte                       `protobuf:"bytes,100,opt,name=zstd_payload,json=zstdPayload,proto3" json:"zstd_payload,omitempty"`
	DecodedSize             uint32                       `protobuf:"varint,101,opt,name=decoded_size,json=decodedSize,proto3" json:"decoded_size,omitempty"`
	CollectorName           string                       `protobuf:"bytes,1,opt,name=collector_name,json=collectorName,proto3" json:"collector_name,omitempty"`
	Nodes                   []*NodeInfo                  `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	TransportStatsSupported bool                         `protobuf:"varint,3,opt,name=transport_stats_supported,json=transportStatsSupported,proto3" json:"transport_stats_supported,omitempty"`
	TransportStats          []*TransportCompressionStats `protobuf:"bytes,4,rep,name=transport_stats,json=transportStats,proto3" json:"transport_stats,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_madtom_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_madtom_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_madtom_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *ListNodesResponse) GetZstdPayload() []byte {
	if x != nil {
		return x.ZstdPayload
	}
	return nil
}

func (x *ListNodesResponse) GetDecodedSize() uint32 {
	if x != nil {
		return x.DecodedSize
	}
	return 0
}

func (x *ListNodesResponse) GetCollectorName() string {
	if x != nil {
		return x.CollectorName
	}
	return ""
}

func (x *ListNodesResponse) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ListNodesResponse) GetTransportStatsSupported() bool {
	if x != nil {
		return x.TransportStatsSupported
	}
	return false
}

func (x *ListNodesResponse) GetTransportStats() []*TransportCompressionStats {
	if x != nil {
		return x.TransportStats
	}
	return nil
}

type RangeQueryRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	MetricName        string                 `protobuf:"bytes,2,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"` // e.g., "cpu.total", "memory.available", "nic.eth0.rx_bytes"
	StartTimeUnixNano int64                  `protobuf:"varint,3,opt,name=start_time_unix_nano,json=startTimeUnixNano,proto3" json:"start_time_unix_nano,omitempty"`
	EndTimeUnixNano   int64                  `protobuf:"varint,4,opt,name=end_time_unix_nano,json=endTimeUnixNano,proto3" json:"end_time_unix_nano,omitempty"`
	TargetPoints      uint32                 `protobuf:"varint,5,opt,name=target_points,json=targetPoints,proto3" json:"target_points,omitempty"` // LOD downsample budget (e.g. 1200)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RangeQueryRequest) Reset() {
	*x = RangeQueryRequest{}
	mi := &file_madtom_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeQueryRequest) ProtoMessage() {}

func (x *RangeQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_madtom_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeQueryRequest.ProtoReflect.Descriptor instead.
func (*RangeQueryRequest) Descriptor() ([]byte, []int) {
	return file_madtom_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *RangeQueryRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RangeQueryRequest) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *RangeQueryRequest) GetStartTimeUnixNano() int64 {
	if x != nil {
		return x.StartTimeUnixNano
	}
	return 0
}

func (x *RangeQueryRequest) GetEndTimeUnixNano() int64 {
	if x != nil {
		return x.EndTimeUnixNano
	}
	return 0
}

func (x *RangeQueryRequest) GetTargetPoints() uint32 {
	if x != nil {
		return x.TargetPoints
	}
	return 0
}

type TimeSeriesPoint struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TimestampUnixNano int64                  `protobuf:"varint,1,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	Value             float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	MinValue          float64                `protobuf:"fixed64,3,opt,name=min_value,json=minValue,proto3" json:"min_value,omitempty"`
	MaxValue          float64                `protobuf:"fixed64,4,opt,name=max_value,json=maxValue,proto3" json:"max_value,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TimeSeriesPoint) Reset() {
	*x = TimeSeriesPoint{}
	mi := &file_madtom_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSeriesPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSeriesPoint) ProtoMessage() {}

func (x *TimeSeriesPoint) ProtoReflect() protoreflect.Message {
	mi := &file_madtom_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSeriesPoint.ProtoReflect.Descriptor instead.
func (*TimeSeriesPoint) Descriptor() ([]byte, []int) {
	return file_madtom_v1_query_proto_rawDescGZIP(), []int{4}
}

func (x *TimeSeriesPoint) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

func (x *TimeSeriesPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TimeSeriesPoint) GetMinValue() float64 {
	if x != nil {
		return x.MinValue
	}
	return 0
}

func (x *TimeSeriesPoint) GetMaxValue() float64 {
	if x != nil {
		return x.MaxValue
	}
	return 0
}

type RangeQueryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Negotiated response envelope; decoded content is this same message type.
	ZstdPayload   []byte             `protobuf:"bytes,100,opt,name=zstd_payload,json=zstdPayload,proto3" json:"zstd_payload,omitempty"`
	DecodedSize   uint32             `protobuf:"varint,101,opt,name=decoded_size,json=decodedSize,proto3" json:"decoded_size,omitempty"`
	NodeId        string             `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	MetricName    string             `protobuf:"bytes,2,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	Points        []*TimeSeriesPoint `protobuf:"bytes,3,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeQueryResponse) Reset() {
	*x = RangeQueryResponse{}
	mi := &file_madtom_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeQueryResponse) ProtoMessage() {}

func (x *RangeQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_madtom_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeQueryResponse.ProtoReflect.Descriptor instead.
func (*RangeQueryResponse) Descriptor() ([]byte, []int) {
	return file_madtom_v1_query_proto_rawDescGZIP(), []int{5}
}

func (x *RangeQueryResponse) GetZstdPayload() []byte {
	if x != nil {
		return x.ZstdPayload
	}
	return nil
}

func (x *RangeQueryResponse) GetDecodedSize() uint32 {
	if x != nil {
		return x.DecodedSize
	}
	return 0
}

func (x *RangeQueryResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RangeQueryResponse) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *RangeQueryResponse) GetPoints() []*TimeSeriesPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type LiveSubscriptionRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	NodeId               string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	SubscribedCategories []string               `protobuf:"bytes,2,rep,name=subscribed_categories,json=subscribedCategories,proto3" json:"subscribed_categories,omitempty"` // "cpu", "memory", "power", "network"
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *LiveSubscriptionRequest) Reset() {
	*x = LiveSubscriptionRequest{}
	mi := &file_madtom_v1_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveSubscriptionRequest) ProtoMessage() {}

func (x *LiveSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_madtom_v1_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*LiveSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_madtom_v1_query_proto_rawDescGZIP(), []int{6}
}

func (x *LiveSubscriptionRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *LiveSubscriptionRequest) GetSubscribedCategories() []string {
	if x != nil {
		return x.SubscribedCategories
	}
	return nil
}

type LiveTelemetryEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Negotiated response envelope; decoded content is this same message type.
	ZstdPayload   []byte         `protobuf:"bytes,100,opt,name=zstd_payload,json=zstdPayload,proto3" json:"zstd_payload,omitempty"`
	DecodedSize   uint32         `protobuf:"varint,101,opt,name=decoded_size,json=decodedSize,proto3" json:"decoded_size,omitempty"`
	NodeId        string         `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CollectorName string         `protobuf:"bytes,2,opt,name=collector_name,json=collectorName,proto3" json:"collector_name,omitempty"`
	Metrics       *SystemMetrics `protobuf:"bytes,3,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveTelemetryEvent) Reset() {
	*x = LiveTelemetryEvent{}
	mi := &file_madtom_v1_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveTelemetryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveTelemetryEvent) ProtoMessage() {}

func (x *LiveTelemetryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_madtom_v1_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveTelemetryEvent.ProtoReflect.Descriptor instead.
func (*LiveTelemetryEvent) Descriptor() ([]byte, []int) {
	return file_madtom_v1_query_proto_rawDescGZIP(), []int{7}
}

func (x *LiveTelemetryEvent) GetZstdPayload() []byte {
	if x != nil {
		return x.ZstdPayload
	}
	return nil
}

func (x *LiveTelemetryEvent) GetDecodedSize() uint32 {
	if x != nil {
		return x.DecodedSize
	}
	return 0
}

func (x *LiveTelemetryEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *LiveTelemetryEvent) GetCollectorName() string {
	if x != nil {
		return x.CollectorName
	}
	return ""
}

func (x *LiveTelemetryEvent) GetMetrics() *SystemMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// Collector-lifetime successfully decoded incoming payloads, including retries.
// Zstd ratio uses only compressed frames; bytes exclude outer protobuf/framing.
type TransportCompressionStats struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Mode              string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Batches           uint64                 `protobuf:"varint,3,opt,name=batches,proto3" json:"batches,omitempty"`
	ZstdBatches       uint64                 `protobuf:"varint,4,opt,name=zstd_batches,json=zstdBatches,proto3" json:"zstd_batches,omitempty"`
	ZstdBytes         uint64                 `protobuf:"varint,5,opt,name=zstd_bytes,json=zstdBytes,proto3" json:"zstd_bytes,omitempty"`
	DecodedZstdBytes  uint64                 `protobuf:"varint,6,opt,name=decoded_zstd_bytes,json=decodedZstdBytes,proto3" json:"decoded_zstd_bytes,omitempty"`
	LastSeenUnixNano  int64                  `protobuf:"varint,7,opt,name=last_seen_unix_nano,json=lastSeenUnixNano,proto3" json:"last_seen_unix_nano,omitempty"`
	RawBytes          uint64                 `protobuf:"varint,8,opt,name=raw_bytes,json=rawBytes,proto3" json:"raw_bytes,omitempty"` // Serialized samples in frames sent without zstd.
	RawBytesSupported bool                   `protobuf:"varint,9,opt,name=raw_bytes_supported,json=rawBytesSupported,proto3" json:"raw_bytes_supported,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TransportCompressionStats) Reset() {
	*x = TransportCompressionStats{}
	mi := &file_madtom_v1_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransportCompressionStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportCompressionStats) ProtoMessage() {}

func (x *TransportCompressionStats) ProtoReflect() protoreflect.Message {
	mi := &file_madtom_v1_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportCompressionStats.ProtoReflect.Descriptor instead.
func (*TransportCompressionStats) Descriptor() ([]byte, []int) {
	return file_madtom_v1_query_proto_rawDescGZIP(), []int{8}
}

func (x *TransportCompressionStats) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *TransportCompressionStats) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *TransportCompressionStats) GetBatches() uint64 {
	if x != nil {
		return x.Batches
	}
	return 0
}

func (x *TransportCompressionStats) GetZstdBatches() uint64 {
	if x != nil {
		return x.ZstdBatches
	}
	return 0
}

func (x *TransportCompressionStats) GetZstdBytes() uint64 {
	if x != nil {
		return x.ZstdBytes
	}
	return 0
}

func (x *TransportCompressionStats) GetDecodedZstdBytes() uint64 {
	if x != nil {
		return x.DecodedZstdBytes
	}
	return 0
}

func (x *TransportCompressionStats) GetLastSeenUnixNano() int64 {
	if x != nil {
		return x.LastSeenUnixNano
	}
	return 0
}

func (x *TransportCompressionStats) GetRawBytes() uint64 {
	if x != nil {
		return x.RawBytes
	}
	return 0
}

func (x *TransportCompressionStats) GetRawBytesSupported() bool {
	if x != nil {
		return x.RawBytesSupported
	}
	return false
}

var File_madtom_v1_query_proto protoreflect.FileDescriptor

const file_madtom_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x15madtom/v1/query.proto\x12\tmadtom.v1\x1a\x17madtom/v1/metrics.proto\"\x12\n" +
	"\x10ListNodesRequest\"\xd3\x01\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12-\n" +
	"\x13last_seen_unix_nano\x18\x06 \x01(\x03R\x10lastSeenUnixNano\x12'\n" +
	"\x0fconnection_mode\x18\a \x01(\tR\x0econnectionMode\"\xb6\x02\n" +
	"\x11ListNodesResponse\x12!\n" +
	"\fzstd_payload\x18d \x01(\fR\vzstdPayload\x12!\n" +
	"\fdecoded_size\x18e \x01(\rR\vdecodedSize\x12%\n" +
	"\x0ecollector_name\x18\x01 \x01(\tR\rcollectorName\x12)\n" +
	"\x05nodes\x18\x02 \x03(\v2\x13.madtom.v1.NodeInfoR\x05nodes\x12:\n" +
	"\x19transport_stats_supported\x18\x03 \x01(\bR\x17transportStatsSupported\x12M\n" +
	"\x0ftransport_stats\x18\x04 \x03(\v2$.madtom.v1.TransportCompressionStatsR\x0etransportStats\"\xd0\x01\n" +
	"\x11RangeQueryRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vmetric_name\x18\x02 \x01(\tR\n" +
	"metricName\x12/\n" +
	"\x14start_time_unix_nano\x18\x03 \x01(\x03R\x11startTimeUnixNano\x12+\n" +
	"\x12end_time_unix_nano\x18\x04 \x01(\x03R\x0fendTimeUnixNano\x12#\n" +
	"\rtarget_points\x18\x05 \x01(\rR\ftargetPoints\"\x91\x01\n" +
	"\x0fTimeSeriesPoint\x12.\n" +
	"\x13timestamp_unix_nano\x18\x01 \x01(\x03R\x11timestampUnixNano\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12\x1b\n" +
	"\tmin_value\x18\x03 \x01(\x01R\bminValue\x12\x1b\n" +
	"\tmax_value\x18\x04 \x01(\x01R\bmaxValue\"\xc8\x01\n" +
	"\x12RangeQueryResponse\x12!\n" +
	"\fzstd_payload\x18d \x01(\fR\vzstdPayload\x12!\n" +
	"\fdecoded_size\x18e \x01(\rR\vdecodedSize\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vmetric_name\x18\x02 \x01(\tR\n" +
	"metricName\x122\n" +
	"\x06points\x18\x03 \x03(\v2\x1a.madtom.v1.TimeSeriesPointR\x06points\"g\n" +
	"\x17LiveSubscriptionRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x123\n" +
	"\x15subscribed_categories\x18\x02 \x03(\tR\x14subscribedCategories\"\xce\x01\n" +
	"\x12LiveTelemetryEvent\x12!\n" +
	"\fzstd_payload\x18d \x01(\fR\vzstdPayload\x12!\n" +
	"\fdecoded_size\x18e \x01(\rR\vdecodedSize\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12%\n" +
	"\x0ecollector_name\x18\x02 \x01(\tR\rcollectorName\x122\n" +
	"\ametrics\x18\x03 \x01(\v2\x18.madtom.v1.SystemMetricsR\ametrics\"\xce\x02\n" +
	"\x19TransportCompressionStats\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x18\n" +
	"\abatches\x18\x03 \x01(\x04R\abatches\x12!\n" +
	"\fzstd_batches\x18\x04 \x01(\x04R\vzstdBatches\x12\x1d\n" +
	"\n" +
	"zstd_bytes\x18\x05 \x01(\x04R\tzstdBytes\x12,\n" +
	"\x12decoded_zstd_bytes\x18\x06 \x01(\x04R\x10decodedZstdBytes\x12-\n" +
	"\x13last_seen_unix_nano\x18\a \x01(\x03R\x10lastSeenUnixNano\x12\x1b\n" +
	"\traw_bytes\x18\b \x01(\x04R\brawBytes\x12.\n" +
	"\x13raw_bytes_supported\x18\t \x01(\bR\x11rawBytesSupported2\xf7\x01\n" +
	"\fQueryService\x12F\n" +
	"\tListNodes\x12\x1b.madtom.v1.ListNodesRequest\x1a\x1c.madtom.v1.ListNodesResponse\x12I\n" +
	"\n" +
	"QueryRange\x12\x1c.madtom.v1.RangeQueryRequest\x1a\x1d.madtom.v1.RangeQueryResponse\x12T\n" +
	"\rSubscribeLive\x12\".madtom.v1.LiveSubscriptionRequest\x1a\x1d.madtom.v1.LiveTelemetryEvent0\x01BYZ3github.com/DarkDuck007/madtom/pkg/proto/v1;madtomv1\xaa\x02!MADTOM.Plugins.Telemetry.Proto.V1b\x06proto3"

var (
	file_madtom_v1_query_proto_rawDescOnce sync.Once
	file_madtom_v1_query_proto_rawDescData []byte
)

func file_madtom_v1_query_proto_rawDescGZIP() []byte {
	file_madtom_v1_query_proto_rawDescOnce.Do(func() {
		file_madtom_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_madtom_v1_query_proto_rawDesc), len(file_madtom_v1_query_proto_rawDesc)))
	})
	return file_madtom_v1_query_proto_rawDescData
}

var file_madtom_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_madtom_v1_query_proto_goTypes = []any{
	(*ListNodesRequest)(nil),          // 0: madtom.v1.ListNodesRequest
	(*NodeInfo)(nil),                  // 1: madtom.v1.NodeInfo
	(*ListNodesResponse)(nil),         // 2: madtom.v1.ListNodesResponse
	(*RangeQueryRequest)(nil),         // 3: madtom.v1.RangeQueryRequest
	(*TimeSeriesPoint)(nil),           // 4: madtom.v1.TimeSeriesPoint
	(*RangeQueryResponse)(nil),        // 5: madtom.v1.RangeQueryResponse
	(*LiveSubscriptionRequest)(nil),   // 6: madtom.v1.LiveSubscriptionRequest
	(*LiveTelemetryEvent)(nil),        // 7: madtom.v1.LiveTelemetryEvent
	(*TransportCompressionStats)(nil), // 8: madtom.v1.TransportCompressionStats
	(*SystemMetrics)(nil),             // 9: madtom.v1.SystemMetrics
}
var file_madtom_v1_query_proto_depIdxs = []int32{
	1, // 0: madtom.v1.ListNodesResponse.nodes:type_name -> madtom.v1.NodeInfo
	8, // 1: madtom.v1.ListNodesResponse.transport_stats:type_name -> madtom.v1.TransportCompressionStats
	4, // 2: madtom.v1.RangeQueryResponse.points:type_name -> madtom.v1.TimeSeriesPoint
	9, // 3: madtom.v1.LiveTelemetryEvent.metrics:type_name -> madtom.v1.SystemMetrics
	0, // 4: madtom.v1.QueryService.ListNodes:input_type -> madtom.v1.ListNodesRequest
	3, // 5: madtom.v1.QueryService.QueryRange:input_type -> madtom.v1.RangeQueryRequest
	6, // 6: madtom.v1.QueryService.SubscribeLive:input_type -> madtom.v1.LiveSubscriptionRequest
	2, // 7: madtom.v1.QueryService.ListNodes:output_type -> madtom.v1.ListNodesResponse
	5, // 8: madtom.v1.QueryService.QueryRange:output_type -> madtom.v1.RangeQueryResponse
	7, // 9: madtom.v1.QueryService.SubscribeLive:output_type -> madtom.v1.LiveTelemetryEvent
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_madtom_v1_query_proto_init() }
func file_madtom_v1_query_proto_init() {
	if File_madtom_v1_query_proto != nil {
		return
	}
	file_madtom_v1_metrics_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_madtom_v1_query_proto_rawDesc), len(file_madtom_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_madtom_v1_query_proto_goTypes,
		DependencyIndexes: file_madtom_v1_query_proto_depIdxs,
		MessageInfos:      file_madtom_v1_query_proto_msgTypes,
	}.Build()
	File_madtom_v1_query_proto = out.File
	file_madtom_v1_query_proto_goTypes = nil
	file_madtom_v1_query_proto_depIdxs = nil
}
