<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AvaloniaStatsTaskEnabled>false</AvaloniaStatsTaskEnabled>
    <EnableAvaloniaStatsTask>false</EnableAvaloniaStatsTask>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Core\MADTOM.PluginContracts\MADTOM.PluginContracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Controls.ColorPicker" Version="12.1.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.1" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="ZstdSharp.Port" Version="0.8.7" />
    <PackageReference Include="Google.Protobuf" Version="3.30.0" />
    <PackageReference Include="Grpc.Net.Client" Version="2.67.0" />
    <PackageReference Include="Grpc.Tools" Version="2.69.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="../../../../../MADTOM_GOLANG/proto/madtom/v1/*.proto" ProtoRoot="../../../../../MADTOM_GOLANG/proto" GrpcServices="Client" />
  </ItemGroup>
</Project>
